export const NFL_TEAMS = [
  {name:"Arizona Cardinals",abbr:"ARI",short:"Cardinals"},
  {name:"Atlanta Falcons",abbr:"ATL",short:"Falcons"},
  {name:"Baltimore Ravens",abbr:"BAL",short:"Ravens"},
  {name:"Buffalo Bills",abbr:"BUF",short:"Bills"},
  {name:"Carolina Panthers",abbr:"CAR",short:"Panthers"},
  {name:"Chicago Bears",abbr:"CHI",short:"Bears"},
  {name:"Cincinnati Bengals",abbr:"CIN",short:"Bengals"},
  {name:"Cleveland Browns",abbr:"CLE",short:"Browns"},
  {name:"Dallas Cowboys",abbr:"DAL",short:"Cowboys"},
  {name:"Denver Broncos",abbr:"DEN",short:"Broncos"},
  {name:"Detroit Lions",abbr:"DET",short:"Lions"},
  {name:"Green Bay Packers",abbr:"GB",short:"Packers"},
  {name:"Houston Texans",abbr:"HOU",short:"Texans"},
  {name:"Indianapolis Colts",abbr:"IND",short:"Colts"},
  {name:"Jacksonville Jaguars",abbr:"JAX",short:"Jaguars"},
  {name:"Kansas City Chiefs",abbr:"KC",short:"Chiefs"},
  {name:"Las Vegas Raiders",abbr:"LV",short:"Raiders"},
  {name:"Los Angeles Chargers",abbr:"LAC",short:"Chargers"},
  {name:"Los Angeles Rams",abbr:"LAR",short:"Rams"},
  {name:"Miami Dolphins",abbr:"MIA",short:"Dolphins"},
  {name:"Minnesota Vikings",abbr:"MIN",short:"Vikings"},
  {name:"New England Patriots",abbr:"NE",short:"Patriots"},
  {name:"New Orleans Saints",abbr:"NO",short:"Saints"},
  {name:"New York Giants",abbr:"NYG",short:"Giants"},
  {name:"New York Jets",abbr:"NYJ",short:"Jets"},
  {name:"Philadelphia Eagles",abbr:"PHI",short:"Eagles"},
  {name:"Pittsburgh Steelers",abbr:"PIT",short:"Steelers"},
  {name:"San Francisco 49ers",abbr:"SF",short:"49ers"},
  {name:"Seattle Seahawks",abbr:"SEA",short:"Seahawks"},
  {name:"Tampa Bay Buccaneers",abbr:"TB",short:"Buccaneers"},
  {name:"Tennessee Titans",abbr:"TEN",short:"Titans"},
  {name:"Washington Commanders",abbr:"WSH",short:"Commanders"},
];

export const NFL_ROSTERS = [
  // ── Arizona Cardinals ──
  {name:"Kyler Murray",pos:"QB",teamAbbr:"ARI"},
  {name:"James Conner",pos:"RB",teamAbbr:"ARI"},
  {name:"Emari Demercado",pos:"RB",teamAbbr:"ARI"},
  {name:"Marvin Harrison Jr.",pos:"WR",teamAbbr:"ARI"},
  {name:"Michael Wilson",pos:"WR",teamAbbr:"ARI"},
  {name:"Greg Dortch",pos:"WR",teamAbbr:"ARI"},
  {name:"Trey McBride",pos:"TE",teamAbbr:"ARI"},
  {name:"Matt Prater",pos:"K",teamAbbr:"ARI"},
  {name:"Zaven Collins",pos:"LB",teamAbbr:"ARI"},
  {name:"BJ Ojulari",pos:"LB",teamAbbr:"ARI"},
  {name:"Dennis Gardeck",pos:"LB",teamAbbr:"ARI"},
  {name:"Mack Wilson",pos:"LB",teamAbbr:"ARI"},
  {name:"Roy Lopez",pos:"DT",teamAbbr:"ARI"},
  {name:"Dante Stills",pos:"DT",teamAbbr:"ARI"},
  {name:"Xavier Thomas",pos:"DE",teamAbbr:"ARI"},
  {name:"Kyzir White",pos:"LB",teamAbbr:"ARI"},
  {name:"Budda Baker",pos:"S",teamAbbr:"ARI"},
  {name:"Jalen Thompson",pos:"S",teamAbbr:"ARI"},
  {name:"Sean Murphy-Bunting",pos:"CB",teamAbbr:"ARI"},
  {name:"Starling Thomas V",pos:"CB",teamAbbr:"ARI"},

  // ── Atlanta Falcons ──
  {name:"Kirk Cousins",pos:"QB",teamAbbr:"ATL"},
  {name:"Bijan Robinson",pos:"RB",teamAbbr:"ATL"},
  {name:"Tyler Allgeier",pos:"RB",teamAbbr:"ATL"},
  {name:"Drake London",pos:"WR",teamAbbr:"ATL"},
  {name:"Darnell Mooney",pos:"WR",teamAbbr:"ATL"},
  {name:"Ray-Ray McCloud",pos:"WR",teamAbbr:"ATL"},
  {name:"Kyle Pitts",pos:"TE",teamAbbr:"ATL"},
  {name:"Younghoe Koo",pos:"K",teamAbbr:"ATL"},
  {name:"Matthew Judon",pos:"LB",teamAbbr:"ATL"},
  {name:"Arnold Ebiketie",pos:"LB",teamAbbr:"ATL"},
  {name:"Nate Landman",pos:"LB",teamAbbr:"ATL"},
  {name:"Grady Jarrett",pos:"DT",teamAbbr:"ATL"},
  {name:"David Onyemata",pos:"DT",teamAbbr:"ATL"},
  {name:"Ruke Orhorhoro",pos:"DT",teamAbbr:"ATL"},
  {name:"Lorenzo Carter",pos:"DE",teamAbbr:"ATL"},
  {name:"Jessie Bates III",pos:"S",teamAbbr:"ATL"},
  {name:"DeMarcco Hellams",pos:"S",teamAbbr:"ATL"},
  {name:"Mike Hughes",pos:"CB",teamAbbr:"ATL"},
  {name:"Jeff Okudah",pos:"CB",teamAbbr:"ATL"},

  // ── Baltimore Ravens ──
  {name:"Lamar Jackson",pos:"QB",teamAbbr:"BAL"},
  {name:"Derrick Henry",pos:"RB",teamAbbr:"BAL"},
  {name:"Justice Hill",pos:"RB",teamAbbr:"BAL"},
  {name:"Zay Flowers",pos:"WR",teamAbbr:"BAL"},
  {name:"Nelson Agholor",pos:"WR",teamAbbr:"BAL"},
  {name:"Devontez Walker",pos:"WR",teamAbbr:"BAL"},
  {name:"Mark Andrews",pos:"TE",teamAbbr:"BAL"},
  {name:"Isaiah Likely",pos:"TE",teamAbbr:"BAL"},
  {name:"Justin Tucker",pos:"K",teamAbbr:"BAL"},
  {name:"Roquan Smith",pos:"LB",teamAbbr:"BAL"},
  {name:"Patrick Queen",pos:"LB",teamAbbr:"BAL"},
  {name:"David Ojabo",pos:"LB",teamAbbr:"BAL"},
  {name:"Odafe Oweh",pos:"LB",teamAbbr:"BAL"},
  {name:"Kyle Van Noy",pos:"LB",teamAbbr:"BAL"},
  {name:"Michael Pierce",pos:"DT",teamAbbr:"BAL"},
  {name:"Travis Jones",pos:"DT",teamAbbr:"BAL"},
  {name:"Broderick Washington",pos:"DT",teamAbbr:"BAL"},
  {name:"Kyle Hamilton",pos:"S",teamAbbr:"BAL"},
  {name:"Marcus Williams",pos:"S",teamAbbr:"BAL"},
  {name:"Marlon Humphrey",pos:"CB",teamAbbr:"BAL"},
  {name:"Brandon Stephens",pos:"CB",teamAbbr:"BAL"},
  {name:"Nate Wiggins",pos:"CB",teamAbbr:"BAL"},

  // ── Buffalo Bills ──
  {name:"Josh Allen",pos:"QB",teamAbbr:"BUF"},
  {name:"James Cook",pos:"RB",teamAbbr:"BUF"},
  {name:"Ray Davis",pos:"RB",teamAbbr:"BUF"},
  {name:"Stefon Diggs",pos:"WR",teamAbbr:"BUF"},
  {name:"Khalil Shakir",pos:"WR",teamAbbr:"BUF"},
  {name:"Keon Coleman",pos:"WR",teamAbbr:"BUF"},
  {name:"Dalton Kincaid",pos:"TE",teamAbbr:"BUF"},
  {name:"Dawson Knox",pos:"TE",teamAbbr:"BUF"},
  {name:"Tyler Bass",pos:"K",teamAbbr:"BUF"},
  {name:"Von Miller",pos:"LB",teamAbbr:"BUF"},
  {name:"AJ Epenesa",pos:"DE",teamAbbr:"BUF"},
  {name:"Greg Rousseau",pos:"DE",teamAbbr:"BUF"},
  {name:"Ed Oliver",pos:"DT",teamAbbr:"BUF"},
  {name:"DaQuan Jones",pos:"DT",teamAbbr:"BUF"},
  {name:"Matt Milano",pos:"LB",teamAbbr:"BUF"},
  {name:"Dorian Williams",pos:"LB",teamAbbr:"BUF"},
  {name:"Taylor Rapp",pos:"S",teamAbbr:"BUF"},
  {name:"Micah Hyde",pos:"S",teamAbbr:"BUF"},
  {name:"Taron Johnson",pos:"CB",teamAbbr:"BUF"},
  {name:"Christian Benford",pos:"CB",teamAbbr:"BUF"},

  // ── Carolina Panthers ──
  {name:"Bryce Young",pos:"QB",teamAbbr:"CAR"},
  {name:"Chuba Hubbard",pos:"RB",teamAbbr:"CAR"},
  {name:"Miles Sanders",pos:"RB",teamAbbr:"CAR"},
  {name:"Adam Thielen",pos:"WR",teamAbbr:"CAR"},
  {name:"Diontae Johnson",pos:"WR",teamAbbr:"CAR"},
  {name:"Xavier Legette",pos:"WR",teamAbbr:"CAR"},
  {name:"Tommy Tremble",pos:"TE",teamAbbr:"CAR"},
  {name:"Eddy Pineiro",pos:"K",teamAbbr:"CAR"},
  {name:"Brian Burns",pos:"DE",teamAbbr:"CAR"},
  {name:"Derrick Brown",pos:"DT",teamAbbr:"CAR"},
  {name:"Shy Tuttle",pos:"DT",teamAbbr:"CAR"},
  {name:"Jadeveon Clowney",pos:"DE",teamAbbr:"CAR"},
  {name:"Frankie Luvu",pos:"LB",teamAbbr:"CAR"},
  {name:"Josey Jewell",pos:"LB",teamAbbr:"CAR"},
  {name:"Jeremy Chinn",pos:"S",teamAbbr:"CAR"},
  {name:"Xavier Woods",pos:"S",teamAbbr:"CAR"},
  {name:"Jaycee Horn",pos:"CB",teamAbbr:"CAR"},
  {name:"Donte Jackson",pos:"CB",teamAbbr:"CAR"},

  // ── Chicago Bears ──
  {name:"Caleb Williams",pos:"QB",teamAbbr:"CHI"},
  {name:"D'Andre Swift",pos:"RB",teamAbbr:"CHI"},
  {name:"Khalil Herbert",pos:"RB",teamAbbr:"CHI"},
  {name:"DJ Moore",pos:"WR",teamAbbr:"CHI"},
  {name:"Keenan Allen",pos:"WR",teamAbbr:"CHI"},
  {name:"Rome Odunze",pos:"WR",teamAbbr:"CHI"},
  {name:"Cole Kmet",pos:"TE",teamAbbr:"CHI"},
  {name:"Cairo Santos",pos:"K",teamAbbr:"CHI"},
  {name:"Montez Sweat",pos:"DE",teamAbbr:"CHI"},
  {name:"DeMarcus Walker",pos:"DE",teamAbbr:"CHI"},
  {name:"Andrew Billings",pos:"DT",teamAbbr:"CHI"},
  {name:"Gervon Dexter",pos:"DT",teamAbbr:"CHI"},
  {name:"Tremaine Edmunds",pos:"LB",teamAbbr:"CHI"},
  {name:"TJ Edwards",pos:"LB",teamAbbr:"CHI"},
  {name:"Dominique Robinson",pos:"DE",teamAbbr:"CHI"},
  {name:"Kevin Byard",pos:"S",teamAbbr:"CHI"},
  {name:"Jaquan Brisker",pos:"S",teamAbbr:"CHI"},
  {name:"Jaylon Johnson",pos:"CB",teamAbbr:"CHI"},
  {name:"Tyrique Stevenson",pos:"CB",teamAbbr:"CHI"},

  // ── Cincinnati Bengals ──
  {name:"Joe Burrow",pos:"QB",teamAbbr:"CIN"},
  {name:"Zack Moss",pos:"RB",teamAbbr:"CIN"},
  {name:"Chase Brown",pos:"RB",teamAbbr:"CIN"},
  {name:"Ja'Marr Chase",pos:"WR",teamAbbr:"CIN"},
  {name:"Tee Higgins",pos:"WR",teamAbbr:"CIN"},
  {name:"Tyler Boyd",pos:"WR",teamAbbr:"CIN"},
  {name:"Mike Gesicki",pos:"TE",teamAbbr:"CIN"},
  {name:"Drew Sample",pos:"TE",teamAbbr:"CIN"},
  {name:"Evan McPherson",pos:"K",teamAbbr:"CIN"},
  {name:"Trey Hendrickson",pos:"DE",teamAbbr:"CIN"},
  {name:"Sam Hubbard",pos:"DE",teamAbbr:"CIN"},
  {name:"BJ Hill",pos:"DT",teamAbbr:"CIN"},
  {name:"Kris Jenkins",pos:"DT",teamAbbr:"CIN"},
  {name:"Logan Wilson",pos:"LB",teamAbbr:"CIN"},
  {name:"Germaine Pratt",pos:"LB",teamAbbr:"CIN"},
  {name:"Joseph Ossai",pos:"LB",teamAbbr:"CIN"},
  {name:"Vonn Bell",pos:"S",teamAbbr:"CIN"},
  {name:"Geno Stone",pos:"S",teamAbbr:"CIN"},
  {name:"Mike Hilton",pos:"CB",teamAbbr:"CIN"},
  {name:"Cam Taylor-Britt",pos:"CB",teamAbbr:"CIN"},

  // ── Cleveland Browns ──
  {name:"Deshaun Watson",pos:"QB",teamAbbr:"CLE"},
  {name:"Nick Chubb",pos:"RB",teamAbbr:"CLE"},
  {name:"Jerome Ford",pos:"RB",teamAbbr:"CLE"},
  {name:"Jerry Jeudy",pos:"WR",teamAbbr:"CLE"},
  {name:"Amari Cooper",pos:"WR",teamAbbr:"CLE"},
  {name:"Elijah Moore",pos:"WR",teamAbbr:"CLE"},
  {name:"David Njoku",pos:"TE",teamAbbr:"CLE"},
  {name:"Dustin Hopkins",pos:"K",teamAbbr:"CLE"},
  {name:"Myles Garrett",pos:"DE",teamAbbr:"CLE"},
  {name:"Za'Darius Smith",pos:"DE",teamAbbr:"CLE"},
  {name:"Dalvin Tomlinson",pos:"DT",teamAbbr:"CLE"},
  {name:"Maurice Hurst",pos:"DT",teamAbbr:"CLE"},
  {name:"Jeremiah Owusu-Koramoah",pos:"LB",teamAbbr:"CLE"},
  {name:"Jordan Hicks",pos:"LB",teamAbbr:"CLE"},
  {name:"Mohamoud Diabate",pos:"LB",teamAbbr:"CLE"},
  {name:"Juan Thornhill",pos:"S",teamAbbr:"CLE"},
  {name:"Rodney McLeod",pos:"S",teamAbbr:"CLE"},
  {name:"Denzel Ward",pos:"CB",teamAbbr:"CLE"},
  {name:"Greg Newsome II",pos:"CB",teamAbbr:"CLE"},
  {name:"Martin Emerson Jr.",pos:"CB",teamAbbr:"CLE"},

  // ── Dallas Cowboys ──
  {name:"Dak Prescott",pos:"QB",teamAbbr:"DAL"},
  {name:"Tony Pollard",pos:"RB",teamAbbr:"DAL"},
  {name:"Rico Dowdle",pos:"RB",teamAbbr:"DAL"},
  {name:"CeeDee Lamb",pos:"WR",teamAbbr:"DAL"},
  {name:"Brandin Cooks",pos:"WR",teamAbbr:"DAL"},
  {name:"Jalen Tolbert",pos:"WR",teamAbbr:"DAL"},
  {name:"Jake Ferguson",pos:"TE",teamAbbr:"DAL"},
  {name:"Brandon Aubrey",pos:"K",teamAbbr:"DAL"},
  {name:"Micah Parsons",pos:"LB",teamAbbr:"DAL"},
  {name:"DeMarcus Lawrence",pos:"DE",teamAbbr:"DAL"},
  {name:"Dante Fowler Jr.",pos:"DE",teamAbbr:"DAL"},
  {name:"Osa Odighizuwa",pos:"DT",teamAbbr:"DAL"},
  {name:"Mazi Smith",pos:"DT",teamAbbr:"DAL"},
  {name:"Eric Kendricks",pos:"LB",teamAbbr:"DAL"},
  {name:"Marist Liufau",pos:"LB",teamAbbr:"DAL"},
  {name:"Jayron Kearse",pos:"S",teamAbbr:"DAL"},
  {name:"Malik Hooker",pos:"S",teamAbbr:"DAL"},
  {name:"Trevon Diggs",pos:"CB",teamAbbr:"DAL"},
  {name:"DaRon Bland",pos:"CB",teamAbbr:"DAL"},
  {name:"Jourdan Lewis",pos:"CB",teamAbbr:"DAL"},

  // ── Denver Broncos ──
  {name:"Bo Nix",pos:"QB",teamAbbr:"DEN"},
  {name:"Jaleel McLaughlin",pos:"RB",teamAbbr:"DEN"},
  {name:"Audric Estime",pos:"RB",teamAbbr:"DEN"},
  {name:"Courtland Sutton",pos:"WR",teamAbbr:"DEN"},
  {name:"Marvin Mims Jr.",pos:"WR",teamAbbr:"DEN"},
  {name:"Josh Reynolds",pos:"WR",teamAbbr:"DEN"},
  {name:"Greg Dulcich",pos:"TE",teamAbbr:"DEN"},
  {name:"Adam Trautman",pos:"TE",teamAbbr:"DEN"},
  {name:"Wil Lutz",pos:"K",teamAbbr:"DEN"},
  {name:"Nik Bonitto",pos:"LB",teamAbbr:"DEN"},
  {name:"Baron Browning",pos:"LB",teamAbbr:"DEN"},
  {name:"Jonathon Cooper",pos:"DE",teamAbbr:"DEN"},
  {name:"Zach Allen",pos:"DE",teamAbbr:"DEN"},
  {name:"DJ Jones",pos:"DT",teamAbbr:"DEN"},
  {name:"Mike Purcell",pos:"DT",teamAbbr:"DEN"},
  {name:"Alex Singleton",pos:"LB",teamAbbr:"DEN"},
  {name:"Patrick Surtain II",pos:"CB",teamAbbr:"DEN"},
  {name:"Ja'Quan McMillian",pos:"CB",teamAbbr:"DEN"},
  {name:"Brandon Jones",pos:"S",teamAbbr:"DEN"},
  {name:"PJ Locke",pos:"S",teamAbbr:"DEN"},

  // ── Detroit Lions ──
  {name:"Jared Goff",pos:"QB",teamAbbr:"DET"},
  {name:"David Montgomery",pos:"RB",teamAbbr:"DET"},
  {name:"Jahmyr Gibbs",pos:"RB",teamAbbr:"DET"},
  {name:"Amon-Ra St. Brown",pos:"WR",teamAbbr:"DET"},
  {name:"Jameson Williams",pos:"WR",teamAbbr:"DET"},
  {name:"Josh Reynolds",pos:"WR",teamAbbr:"DET"},
  {name:"Sam LaPorta",pos:"TE",teamAbbr:"DET"},
  {name:"Jake Bates",pos:"K",teamAbbr:"DET"},
  {name:"Aidan Hutchinson",pos:"DE",teamAbbr:"DET"},
  {name:"Marcus Davenport",pos:"DE",teamAbbr:"DET"},
  {name:"Alim McNeill",pos:"DT",teamAbbr:"DET"},
  {name:"DJ Reader",pos:"DT",teamAbbr:"DET"},
  {name:"Alex Anzalone",pos:"LB",teamAbbr:"DET"},
  {name:"Malcolm Rodriguez",pos:"LB",teamAbbr:"DET"},
  {name:"James Houston",pos:"LB",teamAbbr:"DET"},
  {name:"Kerby Joseph",pos:"S",teamAbbr:"DET"},
  {name:"Brian Branch",pos:"S",teamAbbr:"DET"},
  {name:"Carlton Davis",pos:"CB",teamAbbr:"DET"},
  {name:"Terrion Arnold",pos:"CB",teamAbbr:"DET"},

  // ── Green Bay Packers ──
  {name:"Jordan Love",pos:"QB",teamAbbr:"GB"},
  {name:"Josh Jacobs",pos:"RB",teamAbbr:"GB"},
  {name:"AJ Dillon",pos:"RB",teamAbbr:"GB"},
  {name:"Jayden Reed",pos:"WR",teamAbbr:"GB"},
  {name:"Christian Watson",pos:"WR",teamAbbr:"GB"},
  {name:"Romeo Doubs",pos:"WR",teamAbbr:"GB"},
  {name:"Tucker Kraft",pos:"TE",teamAbbr:"GB"},
  {name:"Luke Musgrave",pos:"TE",teamAbbr:"GB"},
  {name:"Brayden Narveson",pos:"K",teamAbbr:"GB"},
  {name:"Rashan Gary",pos:"LB",teamAbbr:"GB"},
  {name:"Preston Smith",pos:"LB",teamAbbr:"GB"},
  {name:"Lukas Van Ness",pos:"LB",teamAbbr:"GB"},
  {name:"Kenny Clark",pos:"DT",teamAbbr:"GB"},
  {name:"Devonte Wyatt",pos:"DT",teamAbbr:"GB"},
  {name:"De'Vondre Campbell",pos:"LB",teamAbbr:"GB"},
  {name:"Eric Wilson",pos:"LB",teamAbbr:"GB"},
  {name:"Darnell Savage",pos:"S",teamAbbr:"GB"},
  {name:"Xavier McKinney",pos:"S",teamAbbr:"GB"},
  {name:"Jaire Alexander",pos:"CB",teamAbbr:"GB"},
  {name:"Carrington Valentine",pos:"CB",teamAbbr:"GB"},

  // ── Houston Texans ──
  {name:"CJ Stroud",pos:"QB",teamAbbr:"HOU"},
  {name:"Joe Mixon",pos:"RB",teamAbbr:"HOU"},
  {name:"Dameon Pierce",pos:"RB",teamAbbr:"HOU"},
  {name:"Nico Collins",pos:"WR",teamAbbr:"HOU"},
  {name:"Tank Dell",pos:"WR",teamAbbr:"HOU"},
  {name:"Stefon Diggs",pos:"WR",teamAbbr:"HOU"},
  {name:"Dalton Schultz",pos:"TE",teamAbbr:"HOU"},
  {name:"Ka'imi Fairbairn",pos:"K",teamAbbr:"HOU"},
  {name:"Will Anderson Jr.",pos:"DE",teamAbbr:"HOU"},
  {name:"Danielle Hunter",pos:"DE",teamAbbr:"HOU"},
  {name:"Denico Autry",pos:"DE",teamAbbr:"HOU"},
  {name:"Foley Fatukasi",pos:"DT",teamAbbr:"HOU"},
  {name:"Tim Settle",pos:"DT",teamAbbr:"HOU"},
  {name:"Christian Harris",pos:"LB",teamAbbr:"HOU"},
  {name:"Henry To'oTo'o",pos:"LB",teamAbbr:"HOU"},
  {name:"Azeez Al-Shaair",pos:"LB",teamAbbr:"HOU"},
  {name:"Jimmie Ward",pos:"S",teamAbbr:"HOU"},
  {name:"Jalen Pitre",pos:"S",teamAbbr:"HOU"},
  {name:"Derek Stingley Jr.",pos:"CB",teamAbbr:"HOU"},
  {name:"Kamari Lassiter",pos:"CB",teamAbbr:"HOU"},

  // ── Indianapolis Colts ──
  {name:"Anthony Richardson",pos:"QB",teamAbbr:"IND"},
  {name:"Jonathan Taylor",pos:"RB",teamAbbr:"IND"},
  {name:"Trey Sermon",pos:"RB",teamAbbr:"IND"},
  {name:"Michael Pittman Jr.",pos:"WR",teamAbbr:"IND"},
  {name:"Josh Downs",pos:"WR",teamAbbr:"IND"},
  {name:"Alec Pierce",pos:"WR",teamAbbr:"IND"},
  {name:"Jelani Woods",pos:"TE",teamAbbr:"IND"},
  {name:"Matt Gay",pos:"K",teamAbbr:"IND"},
  {name:"DeForest Buckner",pos:"DT",teamAbbr:"IND"},
  {name:"Grover Stewart",pos:"DT",teamAbbr:"IND"},
  {name:"Kwity Paye",pos:"DE",teamAbbr:"IND"},
  {name:"Dayo Odeyingbo",pos:"DE",teamAbbr:"IND"},
  {name:"Shaquille Leonard",pos:"LB",teamAbbr:"IND"},
  {name:"Zaire Franklin",pos:"LB",teamAbbr:"IND"},
  {name:"EJ Speed",pos:"LB",teamAbbr:"IND"},
  {name:"Julian Blackmon",pos:"S",teamAbbr:"IND"},
  {name:"Rodney Thomas II",pos:"S",teamAbbr:"IND"},
  {name:"Kenny Moore II",pos:"CB",teamAbbr:"IND"},
  {name:"JuJu Brents",pos:"CB",teamAbbr:"IND"},

  // ── Jacksonville Jaguars ──
  {name:"Trevor Lawrence",pos:"QB",teamAbbr:"JAX"},
  {name:"Travis Etienne",pos:"RB",teamAbbr:"JAX"},
  {name:"Tank Bigsby",pos:"RB",teamAbbr:"JAX"},
  {name:"Christian Kirk",pos:"WR",teamAbbr:"JAX"},
  {name:"Gabe Davis",pos:"WR",teamAbbr:"JAX"},
  {name:"Brian Thomas Jr.",pos:"WR",teamAbbr:"JAX"},
  {name:"Evan Engram",pos:"TE",teamAbbr:"JAX"},
  {name:"Cameron Dicker",pos:"K",teamAbbr:"JAX"},
  {name:"Josh Hines-Allen",pos:"LB",teamAbbr:"JAX"},
  {name:"Travon Walker",pos:"DE",teamAbbr:"JAX"},
  {name:"Roy Robertson-Harris",pos:"DT",teamAbbr:"JAX"},
  {name:"Maason Smith",pos:"DT",teamAbbr:"JAX"},
  {name:"Foyesade Oluokun",pos:"LB",teamAbbr:"JAX"},
  {name:"Chad Muma",pos:"LB",teamAbbr:"JAX"},
  {name:"Devin Lloyd",pos:"LB",teamAbbr:"JAX"},
  {name:"Andre Cisco",pos:"S",teamAbbr:"JAX"},
  {name:"Daniel Thomas",pos:"S",teamAbbr:"JAX"},
  {name:"Darious Williams",pos:"CB",teamAbbr:"JAX"},
  {name:"Ronald Darby",pos:"CB",teamAbbr:"JAX"},
  {name:"Tyson Campbell",pos:"CB",teamAbbr:"JAX"},

  // ── Kansas City Chiefs ──
  {name:"Patrick Mahomes",pos:"QB",teamAbbr:"KC"},
  {name:"Isiah Pacheco",pos:"RB",teamAbbr:"KC"},
  {name:"Clyde Edwards-Helaire",pos:"RB",teamAbbr:"KC"},
  {name:"Travis Kelce",pos:"TE",teamAbbr:"KC"},
  {name:"Noah Gray",pos:"TE",teamAbbr:"KC"},
  {name:"Rashee Rice",pos:"WR",teamAbbr:"KC"},
  {name:"Hollywood Brown",pos:"WR",teamAbbr:"KC"},
  {name:"Justin Watson",pos:"WR",teamAbbr:"KC"},
  {name:"Harrison Butker",pos:"K",teamAbbr:"KC"},
  {name:"Chris Jones",pos:"DT",teamAbbr:"KC"},
  {name:"Derrick Nnadi",pos:"DT",teamAbbr:"KC"},
  {name:"George Karlaftis",pos:"DE",teamAbbr:"KC"},
  {name:"Felix Anudike-Uzomah",pos:"DE",teamAbbr:"KC"},
  {name:"Nick Bolton",pos:"LB",teamAbbr:"KC"},
  {name:"Willie Gay Jr.",pos:"LB",teamAbbr:"KC"},
  {name:"Drue Tranquill",pos:"LB",teamAbbr:"KC"},
  {name:"Bryan Cook",pos:"S",teamAbbr:"KC"},
  {name:"Mike Edwards",pos:"S",teamAbbr:"KC"},
  {name:"Trent McDuffie",pos:"CB",teamAbbr:"KC"},
  {name:"L'Jarius Sneed",pos:"CB",teamAbbr:"KC"},
  {name:"Joshua Williams",pos:"CB",teamAbbr:"KC"},

  // ── Las Vegas Raiders ──
  {name:"Aidan O'Connell",pos:"QB",teamAbbr:"LV"},
  {name:"Alexander Mattison",pos:"RB",teamAbbr:"LV"},
  {name:"Zamir White",pos:"RB",teamAbbr:"LV"},
  {name:"Davante Adams",pos:"WR",teamAbbr:"LV"},
  {name:"Jakobi Meyers",pos:"WR",teamAbbr:"LV"},
  {name:"DJ Turner",pos:"WR",teamAbbr:"LV"},
  {name:"Brock Bowers",pos:"TE",teamAbbr:"LV"},
  {name:"Daniel Carlson",pos:"K",teamAbbr:"LV"},
  {name:"Maxx Crosby",pos:"DE",teamAbbr:"LV"},
  {name:"Malcolm Koonce",pos:"DE",teamAbbr:"LV"},
  {name:"Adam Butler",pos:"DT",teamAbbr:"LV"},
  {name:"Jerry Tillery",pos:"DT",teamAbbr:"LV"},
  {name:"Robert Spillane",pos:"LB",teamAbbr:"LV"},
  {name:"Divine Deablo",pos:"LB",teamAbbr:"LV"},
  {name:"Luke Masterson",pos:"LB",teamAbbr:"LV"},
  {name:"Marcus Epps",pos:"S",teamAbbr:"LV"},
  {name:"Isaiah Pola-Mao",pos:"S",teamAbbr:"LV"},
  {name:"Nate Hobbs",pos:"CB",teamAbbr:"LV"},
  {name:"Brandon Facyson",pos:"CB",teamAbbr:"LV"},

  // ── Los Angeles Chargers ──
  {name:"Justin Herbert",pos:"QB",teamAbbr:"LAC"},
  {name:"JK Dobbins",pos:"RB",teamAbbr:"LAC"},
  {name:"Gus Edwards",pos:"RB",teamAbbr:"LAC"},
  {name:"Quentin Johnston",pos:"WR",teamAbbr:"LAC"},
  {name:"Ladd McConkey",pos:"WR",teamAbbr:"LAC"},
  {name:"Joshua Palmer",pos:"WR",teamAbbr:"LAC"},
  {name:"Will Dissly",pos:"TE",teamAbbr:"LAC"},
  {name:"Cameron Dicker",pos:"K",teamAbbr:"LAC"},
  {name:"Khalil Mack",pos:"LB",teamAbbr:"LAC"},
  {name:"Joey Bosa",pos:"DE",teamAbbr:"LAC"},
  {name:"Morgan Fox",pos:"DE",teamAbbr:"LAC"},
  {name:"Sebastian Joseph-Day",pos:"DT",teamAbbr:"LAC"},
  {name:"Scott Matlock",pos:"DT",teamAbbr:"LAC"},
  {name:"Daiyan Henley",pos:"LB",teamAbbr:"LAC"},
  {name:"Eric Kendricks",pos:"LB",teamAbbr:"LAC"},
  {name:"Derwin James",pos:"S",teamAbbr:"LAC"},
  {name:"Alohi Gilman",pos:"S",teamAbbr:"LAC"},
  {name:"Asante Samuel Jr.",pos:"CB",teamAbbr:"LAC"},
  {name:"Kristian Fulton",pos:"CB",teamAbbr:"LAC"},

  // ── Los Angeles Rams ──
  {name:"Matthew Stafford",pos:"QB",teamAbbr:"LAR"},
  {name:"Kyren Williams",pos:"RB",teamAbbr:"LAR"},
  {name:"Blake Corum",pos:"RB",teamAbbr:"LAR"},
  {name:"Cooper Kupp",pos:"WR",teamAbbr:"LAR"},
  {name:"Puka Nacua",pos:"WR",teamAbbr:"LAR"},
  {name:"Demarcus Robinson",pos:"WR",teamAbbr:"LAR"},
  {name:"Tyler Higbee",pos:"TE",teamAbbr:"LAR"},
  {name:"Joshua Karty",pos:"K",teamAbbr:"LAR"},
  {name:"Byron Young",pos:"DE",teamAbbr:"LAR"},
  {name:"Kobie Turner",pos:"DT",teamAbbr:"LAR"},
  {name:"Bobby Brown III",pos:"DT",teamAbbr:"LAR"},
  {name:"Michael Hoecht",pos:"DE",teamAbbr:"LAR"},
  {name:"Ernest Jones IV",pos:"LB",teamAbbr:"LAR"},
  {name:"Christian Rozeboom",pos:"LB",teamAbbr:"LAR"},
  {name:"Omar Speights",pos:"LB",teamAbbr:"LAR"},
  {name:"Kamren Curl",pos:"S",teamAbbr:"LAR"},
  {name:"Jordan Fuller",pos:"S",teamAbbr:"LAR"},
  {name:"Darious Williams",pos:"CB",teamAbbr:"LAR"},
  {name:"Tre'Davious White",pos:"CB",teamAbbr:"LAR"},
  {name:"Ahkello Witherspoon",pos:"CB",teamAbbr:"LAR"},

  // ── Miami Dolphins ──
  {name:"Tua Tagovailoa",pos:"QB",teamAbbr:"MIA"},
  {name:"De'Von Achane",pos:"RB",teamAbbr:"MIA"},
  {name:"Raheem Mostert",pos:"RB",teamAbbr:"MIA"},
  {name:"Tyreek Hill",pos:"WR",teamAbbr:"MIA"},
  {name:"Jaylen Waddle",pos:"WR",teamAbbr:"MIA"},
  {name:"Braxton Berrios",pos:"WR",teamAbbr:"MIA"},
  {name:"Durham Smythe",pos:"TE",teamAbbr:"MIA"},
  {name:"Jason Sanders",pos:"K",teamAbbr:"MIA"},
  {name:"Jaelan Phillips",pos:"DE",teamAbbr:"MIA"},
  {name:"Bradley Chubb",pos:"LB",teamAbbr:"MIA"},
  {name:"Emmanuel Ogbah",pos:"DE",teamAbbr:"MIA"},
  {name:"Zach Sieler",pos:"DT",teamAbbr:"MIA"},
  {name:"Christian Wilkins",pos:"DT",teamAbbr:"MIA"},
  {name:"David Long Jr.",pos:"LB",teamAbbr:"MIA"},
  {name:"Jordan Brooks",pos:"LB",teamAbbr:"MIA"},
  {name:"Jevon Holland",pos:"S",teamAbbr:"MIA"},
  {name:"DeShon Elliott",pos:"S",teamAbbr:"MIA"},
  {name:"Xavien Howard",pos:"CB",teamAbbr:"MIA"},
  {name:"Jalen Ramsey",pos:"CB",teamAbbr:"MIA"},
  {name:"Kader Kohou",pos:"CB",teamAbbr:"MIA"},

  // ── Minnesota Vikings ──
  {name:"Sam Darnold",pos:"QB",teamAbbr:"MIN"},
  {name:"Aaron Jones",pos:"RB",teamAbbr:"MIN"},
  {name:"Ty Chandler",pos:"RB",teamAbbr:"MIN"},
  {name:"Justin Jefferson",pos:"WR",teamAbbr:"MIN"},
  {name:"Jordan Addison",pos:"WR",teamAbbr:"MIN"},
  {name:"Jalen Nailor",pos:"WR",teamAbbr:"MIN"},
  {name:"TJ Hockenson",pos:"TE",teamAbbr:"MIN"},
  {name:"Josh Oliver",pos:"TE",teamAbbr:"MIN"},
  {name:"Will Reichard",pos:"K",teamAbbr:"MIN"},
  {name:"Jonathan Greenard",pos:"DE",teamAbbr:"MIN"},
  {name:"Andrew Van Ginkel",pos:"LB",teamAbbr:"MIN"},
  {name:"Pat Jones II",pos:"DE",teamAbbr:"MIN"},
  {name:"Harrison Phillips",pos:"DT",teamAbbr:"MIN"},
  {name:"Jalen Redmond",pos:"DT",teamAbbr:"MIN"},
  {name:"Ivan Pace Jr.",pos:"LB",teamAbbr:"MIN"},
  {name:"Blake Cashman",pos:"LB",teamAbbr:"MIN"},
  {name:"Harrison Smith",pos:"S",teamAbbr:"MIN"},
  {name:"Josh Metellus",pos:"S",teamAbbr:"MIN"},
  {name:"Byron Murphy II",pos:"CB",teamAbbr:"MIN"},
  {name:"Stephon Gilmore",pos:"CB",teamAbbr:"MIN"},
  {name:"Shaq Griffin",pos:"CB",teamAbbr:"MIN"},

  // ── New England Patriots ──
  {name:"Drake Maye",pos:"QB",teamAbbr:"NE"},
  {name:"Rhamondre Stevenson",pos:"RB",teamAbbr:"NE"},
  {name:"Antonio Gibson",pos:"RB",teamAbbr:"NE"},
  {name:"JuJu Smith-Schuster",pos:"WR",teamAbbr:"NE"},
  {name:"Kendrick Bourne",pos:"WR",teamAbbr:"NE"},
  {name:"Ja'Lynn Polk",pos:"WR",teamAbbr:"NE"},
  {name:"Hunter Henry",pos:"TE",teamAbbr:"NE"},
  {name:"Austin Hooper",pos:"TE",teamAbbr:"NE"},
  {name:"Chad Ryland",pos:"K",teamAbbr:"NE"},
  {name:"Matthew Judon",pos:"LB",teamAbbr:"NE"},
  {name:"Keion White",pos:"DE",teamAbbr:"NE"},
  {name:"Deatrich Wise Jr.",pos:"DE",teamAbbr:"NE"},
  {name:"Christian Barmore",pos:"DT",teamAbbr:"NE"},
  {name:"Davon Godchaux",pos:"DT",teamAbbr:"NE"},
  {name:"Ja'Whaun Bentley",pos:"LB",teamAbbr:"NE"},
  {name:"Raekwon McMillan",pos:"LB",teamAbbr:"NE"},
  {name:"Kyle Dugger",pos:"S",teamAbbr:"NE"},
  {name:"Jabrill Peppers",pos:"S",teamAbbr:"NE"},
  {name:"Christian Gonzalez",pos:"CB",teamAbbr:"NE"},
  {name:"Jonathan Jones",pos:"CB",teamAbbr:"NE"},

  // ── New Orleans Saints ──
  {name:"Derek Carr",pos:"QB",teamAbbr:"NO"},
  {name:"Alvin Kamara",pos:"RB",teamAbbr:"NO"},
  {name:"Kendre Miller",pos:"RB",teamAbbr:"NO"},
  {name:"Chris Olave",pos:"WR",teamAbbr:"NO"},
  {name:"Rashid Shaheed",pos:"WR",teamAbbr:"NO"},
  {name:"AT Perry",pos:"WR",teamAbbr:"NO"},
  {name:"Foster Moreau",pos:"TE",teamAbbr:"NO"},
  {name:"Juwan Johnson",pos:"TE",teamAbbr:"NO"},
  {name:"Blake Grupe",pos:"K",teamAbbr:"NO"},
  {name:"Cameron Jordan",pos:"DE",teamAbbr:"NO"},
  {name:"Carl Granderson",pos:"DE",teamAbbr:"NO"},
  {name:"Bryan Bresee",pos:"DT",teamAbbr:"NO"},
  {name:"Nathan Shepherd",pos:"DT",teamAbbr:"NO"},
  {name:"Demario Davis",pos:"LB",teamAbbr:"NO"},
  {name:"Pete Werner",pos:"LB",teamAbbr:"NO"},
  {name:"Tyrann Mathieu",pos:"S",teamAbbr:"NO"},
  {name:"Jordan Howden",pos:"S",teamAbbr:"NO"},
  {name:"Paulson Adebo",pos:"CB",teamAbbr:"NO"},
  {name:"Alontae Taylor",pos:"CB",teamAbbr:"NO"},

  // ── New York Giants ──
  {name:"Daniel Jones",pos:"QB",teamAbbr:"NYG"},
  {name:"Devin Singletary",pos:"RB",teamAbbr:"NYG"},
  {name:"Eric Gray",pos:"RB",teamAbbr:"NYG"},
  {name:"Malik Nabers",pos:"WR",teamAbbr:"NYG"},
  {name:"Wan'Dale Robinson",pos:"WR",teamAbbr:"NYG"},
  {name:"Darius Slayton",pos:"WR",teamAbbr:"NYG"},
  {name:"Darren Waller",pos:"TE",teamAbbr:"NYG"},
  {name:"Daniel Bellinger",pos:"TE",teamAbbr:"NYG"},
  {name:"Graham Gano",pos:"K",teamAbbr:"NYG"},
  {name:"Brian Burns",pos:"DE",teamAbbr:"NYG"},
  {name:"Dexter Lawrence",pos:"DT",teamAbbr:"NYG"},
  {name:"Rakeem Nunez-Roches",pos:"DT",teamAbbr:"NYG"},
  {name:"Kayvon Thibodeaux",pos:"DE",teamAbbr:"NYG"},
  {name:"Bobby Okereke",pos:"LB",teamAbbr:"NYG"},
  {name:"Micah McFadden",pos:"LB",teamAbbr:"NYG"},
  {name:"Dane Belton",pos:"S",teamAbbr:"NYG"},
  {name:"Jason Pinnock",pos:"S",teamAbbr:"NYG"},
  {name:"Deonte Banks",pos:"CB",teamAbbr:"NYG"},
  {name:"Adoree' Jackson",pos:"CB",teamAbbr:"NYG"},

  // ── New York Jets ──
  {name:"Aaron Rodgers",pos:"QB",teamAbbr:"NYJ"},
  {name:"Breece Hall",pos:"RB",teamAbbr:"NYJ"},
  {name:"Braelon Allen",pos:"RB",teamAbbr:"NYJ"},
  {name:"Garrett Wilson",pos:"WR",teamAbbr:"NYJ"},
  {name:"Mike Williams",pos:"WR",teamAbbr:"NYJ"},
  {name:"Malachi Corley",pos:"WR",teamAbbr:"NYJ"},
  {name:"Tyler Conklin",pos:"TE",teamAbbr:"NYJ"},
  {name:"Jeremy Ruckert",pos:"TE",teamAbbr:"NYJ"},
  {name:"Greg Zuerlein",pos:"K",teamAbbr:"NYJ"},
  {name:"Quinnen Williams",pos:"DT",teamAbbr:"NYJ"},
  {name:"Solomon Thomas",pos:"DT",teamAbbr:"NYJ"},
  {name:"Jermaine Johnson II",pos:"DE",teamAbbr:"NYJ"},
  {name:"Will McDonald IV",pos:"DE",teamAbbr:"NYJ"},
  {name:"CJ Mosley",pos:"LB",teamAbbr:"NYJ"},
  {name:"Jamien Sherwood",pos:"LB",teamAbbr:"NYJ"},
  {name:"Haason Reddick",pos:"LB",teamAbbr:"NYJ"},
  {name:"Tony Adams",pos:"S",teamAbbr:"NYJ"},
  {name:"Jordan Whitehead",pos:"S",teamAbbr:"NYJ"},
  {name:"Sauce Gardner",pos:"CB",teamAbbr:"NYJ"},
  {name:"DJ Reed",pos:"CB",teamAbbr:"NYJ"},

  // ── Philadelphia Eagles ──
  {name:"Jalen Hurts",pos:"QB",teamAbbr:"PHI"},
  {name:"Saquon Barkley",pos:"RB",teamAbbr:"PHI"},
  {name:"Kenneth Gainwell",pos:"RB",teamAbbr:"PHI"},
  {name:"AJ Brown",pos:"WR",teamAbbr:"PHI"},
  {name:"DeVonta Smith",pos:"WR",teamAbbr:"PHI"},
  {name:"Britain Covey",pos:"WR",teamAbbr:"PHI"},
  {name:"Dallas Goedert",pos:"TE",teamAbbr:"PHI"},
  {name:"Jake Elliott",pos:"K",teamAbbr:"PHI"},
  {name:"Jalen Carter",pos:"DT",teamAbbr:"PHI"},
  {name:"Milton Williams",pos:"DT",teamAbbr:"PHI"},
  {name:"Brandon Graham",pos:"DE",teamAbbr:"PHI"},
  {name:"Josh Sweat",pos:"DE",teamAbbr:"PHI"},
  {name:"Haason Reddick",pos:"LB",teamAbbr:"PHI"},
  {name:"Nakobe Dean",pos:"LB",teamAbbr:"PHI"},
  {name:"Zack Baun",pos:"LB",teamAbbr:"PHI"},
  {name:"Reed Blankenship",pos:"S",teamAbbr:"PHI"},
  {name:"Sydney Brown",pos:"S",teamAbbr:"PHI"},
  {name:"Darius Slay",pos:"CB",teamAbbr:"PHI"},
  {name:"James Bradberry",pos:"CB",teamAbbr:"PHI"},
  {name:"Quinyon Mitchell",pos:"CB",teamAbbr:"PHI"},

  // ── Pittsburgh Steelers ──
  {name:"Russell Wilson",pos:"QB",teamAbbr:"PIT"},
  {name:"Najee Harris",pos:"RB",teamAbbr:"PIT"},
  {name:"Jaylen Warren",pos:"RB",teamAbbr:"PIT"},
  {name:"George Pickens",pos:"WR",teamAbbr:"PIT"},
  {name:"Van Jefferson",pos:"WR",teamAbbr:"PIT"},
  {name:"Calvin Austin III",pos:"WR",teamAbbr:"PIT"},
  {name:"Pat Freiermuth",pos:"TE",teamAbbr:"PIT"},
  {name:"Chris Boswell",pos:"K",teamAbbr:"PIT"},
  {name:"TJ Watt",pos:"LB",teamAbbr:"PIT"},
  {name:"Alex Highsmith",pos:"LB",teamAbbr:"PIT"},
  {name:"Cameron Heyward",pos:"DT",teamAbbr:"PIT"},
  {name:"Larry Ogunjobi",pos:"DT",teamAbbr:"PIT"},
  {name:"Montravius Adams",pos:"DT",teamAbbr:"PIT"},
  {name:"Patrick Queen",pos:"LB",teamAbbr:"PIT"},
  {name:"Elandon Roberts",pos:"LB",teamAbbr:"PIT"},
  {name:"Minkah Fitzpatrick",pos:"S",teamAbbr:"PIT"},
  {name:"DeShon Elliott",pos:"S",teamAbbr:"PIT"},
  {name:"Joey Porter Jr.",pos:"CB",teamAbbr:"PIT"},
  {name:"Donte Jackson",pos:"CB",teamAbbr:"PIT"},

  // ── San Francisco 49ers ──
  {name:"Brock Purdy",pos:"QB",teamAbbr:"SF"},
  {name:"Christian McCaffrey",pos:"RB",teamAbbr:"SF"},
  {name:"Jordan Mason",pos:"RB",teamAbbr:"SF"},
  {name:"Deebo Samuel",pos:"WR",teamAbbr:"SF"},
  {name:"Brandon Aiyuk",pos:"WR",teamAbbr:"SF"},
  {name:"Jauan Jennings",pos:"WR",teamAbbr:"SF"},
  {name:"George Kittle",pos:"TE",teamAbbr:"SF"},
  {name:"Jake Moody",pos:"K",teamAbbr:"SF"},
  {name:"Nick Bosa",pos:"DE",teamAbbr:"SF"},
  {name:"Leonard Floyd",pos:"DE",teamAbbr:"SF"},
  {name:"Javon Hargrave",pos:"DT",teamAbbr:"SF"},
  {name:"Maliek Collins",pos:"DT",teamAbbr:"SF"},
  {name:"Fred Warner",pos:"LB",teamAbbr:"SF"},
  {name:"Dre Greenlaw",pos:"LB",teamAbbr:"SF"},
  {name:"De'Vondre Campbell",pos:"LB",teamAbbr:"SF"},
  {name:"Talanoa Hufanga",pos:"S",teamAbbr:"SF"},
  {name:"Ji'Ayir Brown",pos:"S",teamAbbr:"SF"},
  {name:"Charvarius Ward",pos:"CB",teamAbbr:"SF"},
  {name:"Deommodore Lenoir",pos:"CB",teamAbbr:"SF"},
  {name:"Ambry Thomas",pos:"CB",teamAbbr:"SF"},

  // ── Seattle Seahawks ──
  {name:"Geno Smith",pos:"QB",teamAbbr:"SEA"},
  {name:"Zach Charbonnet",pos:"RB",teamAbbr:"SEA"},
  {name:"Kenneth Walker III",pos:"RB",teamAbbr:"SEA"},
  {name:"DK Metcalf",pos:"WR",teamAbbr:"SEA"},
  {name:"Tyler Lockett",pos:"WR",teamAbbr:"SEA"},
  {name:"Jaxon Smith-Njigba",pos:"WR",teamAbbr:"SEA"},
  {name:"Noah Fant",pos:"TE",teamAbbr:"SEA"},
  {name:"Jason Myers",pos:"K",teamAbbr:"SEA"},
  {name:"Leonard Williams",pos:"DT",teamAbbr:"SEA"},
  {name:"Jarran Reed",pos:"DT",teamAbbr:"SEA"},
  {name:"Boye Mafe",pos:"DE",teamAbbr:"SEA"},
  {name:"Dre'Mont Jones",pos:"DE",teamAbbr:"SEA"},
  {name:"Uchenna Nwosu",pos:"LB",teamAbbr:"SEA"},
  {name:"Jerome Baker",pos:"LB",teamAbbr:"SEA"},
  {name:"Tyrel Dodson",pos:"LB",teamAbbr:"SEA"},
  {name:"Jamal Adams",pos:"S",teamAbbr:"SEA"},
  {name:"Julian Love",pos:"S",teamAbbr:"SEA"},
  {name:"Devon Witherspoon",pos:"CB",teamAbbr:"SEA"},
  {name:"Riq Woolen",pos:"CB",teamAbbr:"SEA"},
  {name:"Tre Brown",pos:"CB",teamAbbr:"SEA"},

  // ── Tampa Bay Buccaneers ──
  {name:"Baker Mayfield",pos:"QB",teamAbbr:"TB"},
  {name:"Rachaad White",pos:"RB",teamAbbr:"TB"},
  {name:"Sean Tucker",pos:"RB",teamAbbr:"TB"},
  {name:"Mike Evans",pos:"WR",teamAbbr:"TB"},
  {name:"Chris Godwin",pos:"WR",teamAbbr:"TB"},
  {name:"Trey Palmer",pos:"WR",teamAbbr:"TB"},
  {name:"Cade Otton",pos:"TE",teamAbbr:"TB"},
  {name:"Chase McLaughlin",pos:"K",teamAbbr:"TB"},
  {name:"Vita Vea",pos:"DT",teamAbbr:"TB"},
  {name:"Greg Gaines",pos:"DT",teamAbbr:"TB"},
  {name:"Yaya Diaby",pos:"LB",teamAbbr:"TB"},
  {name:"William Gholston",pos:"DE",teamAbbr:"TB"},
  {name:"Shaquil Barrett",pos:"LB",teamAbbr:"TB"},
  {name:"Lavonte David",pos:"LB",teamAbbr:"TB"},
  {name:"SirVocea Dennis",pos:"LB",teamAbbr:"TB"},
  {name:"Antoine Winfield Jr.",pos:"S",teamAbbr:"TB"},
  {name:"Jordan Whitehead",pos:"S",teamAbbr:"TB"},
  {name:"Jamel Dean",pos:"CB",teamAbbr:"TB"},
  {name:"Zyon McCollum",pos:"CB",teamAbbr:"TB"},
  {name:"Dee Delaney",pos:"CB",teamAbbr:"TB"},

  // ── Tennessee Titans ──
  {name:"Will Levis",pos:"QB",teamAbbr:"TEN"},
  {name:"Tony Pollard",pos:"RB",teamAbbr:"TEN"},
  {name:"Tyjae Spears",pos:"RB",teamAbbr:"TEN"},
  {name:"Calvin Ridley",pos:"WR",teamAbbr:"TEN"},
  {name:"DeAndre Hopkins",pos:"WR",teamAbbr:"TEN"},
  {name:"Tyler Boyd",pos:"WR",teamAbbr:"TEN"},
  {name:"Chigoziem Okonkwo",pos:"TE",teamAbbr:"TEN"},
  {name:"Nick Folk",pos:"K",teamAbbr:"TEN"},
  {name:"Harold Landry III",pos:"LB",teamAbbr:"TEN"},
  {name:"Arden Key",pos:"DE",teamAbbr:"TEN"},
  {name:"Jeffery Simmons",pos:"DT",teamAbbr:"TEN"},
  {name:"Sebastian Joseph-Day",pos:"DT",teamAbbr:"TEN"},
  {name:"Otis Reese IV",pos:"LB",teamAbbr:"TEN"},
  {name:"Jack Gibbens",pos:"LB",teamAbbr:"TEN"},
  {name:"Azeez Al-Shaair",pos:"LB",teamAbbr:"TEN"},
  {name:"Quandre Diggs",pos:"S",teamAbbr:"TEN"},
  {name:"Amani Hooker",pos:"S",teamAbbr:"TEN"},
  {name:"L'Jarius Sneed",pos:"CB",teamAbbr:"TEN"},
  {name:"Darrell Baker Jr.",pos:"CB",teamAbbr:"TEN"},
  {name:"Roger McCreary",pos:"CB",teamAbbr:"TEN"},

  // ── Washington Commanders ──
  {name:"Jayden Daniels",pos:"QB",teamAbbr:"WSH"},
  {name:"Brian Robinson Jr.",pos:"RB",teamAbbr:"WSH"},
  {name:"Austin Ekeler",pos:"RB",teamAbbr:"WSH"},
  {name:"Terry McLaurin",pos:"WR",teamAbbr:"WSH"},
  {name:"Olamide Zaccheaus",pos:"WR",teamAbbr:"WSH"},
  {name:"Noah Brown",pos:"WR",teamAbbr:"WSH"},
  {name:"Logan Thomas",pos:"TE",teamAbbr:"WSH"},
  {name:"Zach Ertz",pos:"TE",teamAbbr:"WSH"},
  {name:"Austin Seibert",pos:"K",teamAbbr:"WSH"},
  {name:"Jonathan Allen",pos:"DT",teamAbbr:"WSH"},
  {name:"Daron Payne",pos:"DT",teamAbbr:"WSH"},
  {name:"Dante Fowler Jr.",pos:"DE",teamAbbr:"WSH"},
  {name:"Clelin Ferrell",pos:"DE",teamAbbr:"WSH"},
  {name:"Bobby Wagner",pos:"LB",teamAbbr:"WSH"},
  {name:"Cody Barton",pos:"LB",teamAbbr:"WSH"},
  {name:"Frankie Luvu",pos:"LB",teamAbbr:"WSH"},
  {name:"Kamren Curl",pos:"S",teamAbbr:"WSH"},
  {name:"Percy Butler",pos:"S",teamAbbr:"WSH"},
  {name:"Emmanuel Forbes",pos:"CB",teamAbbr:"WSH"},
  {name:"Marshon Lattimore",pos:"CB",teamAbbr:"WSH"},
  {name:"Mike Sainristil",pos:"CB",teamAbbr:"WSH"},
];
