// 2026 NFL Rosters — sourced from OurLads.com depth charts (September 2026)
// Updated: Week 1 2026 season

export const NFL_TEAMS = [
  {name:"Arizona Cardinals",abbr:"ARI",short:"Cardinals"},
  {name:"Atlanta Falcons",abbr:"ATL",short:"Falcons"},
  {name:"Baltimore Ravens",abbr:"BAL",short:"Ravens"},
  {name:"Buffalo Bills",abbr:"BUF",short:"Bills"},
  {name:"Carolina Panthers",abbr:"CAR",short:"Panthers"},
  {name:"Chicago Bears",abbr:"CHI",short:"Bears"},
  {name:"Cincinnati Bengals",abbr:"CIN",short:"Bengals"},
  {name:"Cleveland Browns",abbr:"CLE",short:"Browns"},
  {name:"Dallas Cowboys",abbr:"DAL",short:"Cowboys"},
  {name:"Denver Broncos",abbr:"DEN",short:"Broncos"},
  {name:"Detroit Lions",abbr:"DET",short:"Lions"},
  {name:"Green Bay Packers",abbr:"GB",short:"Packers"},
  {name:"Houston Texans",abbr:"HOU",short:"Texans"},
  {name:"Indianapolis Colts",abbr:"IND",short:"Colts"},
  {name:"Jacksonville Jaguars",abbr:"JAX",short:"Jaguars"},
  {name:"Kansas City Chiefs",abbr:"KC",short:"Chiefs"},
  {name:"Las Vegas Raiders",abbr:"LV",short:"Raiders"},
  {name:"Los Angeles Chargers",abbr:"LAC",short:"Chargers"},
  {name:"Los Angeles Rams",abbr:"LAR",short:"Rams"},
  {name:"Miami Dolphins",abbr:"MIA",short:"Dolphins"},
  {name:"Minnesota Vikings",abbr:"MIN",short:"Vikings"},
  {name:"New England Patriots",abbr:"NE",short:"Patriots"},
  {name:"New Orleans Saints",abbr:"NO",short:"Saints"},
  {name:"New York Giants",abbr:"NYG",short:"Giants"},
  {name:"New York Jets",abbr:"NYJ",short:"Jets"},
  {name:"Philadelphia Eagles",abbr:"PHI",short:"Eagles"},
  {name:"Pittsburgh Steelers",abbr:"PIT",short:"Steelers"},
  {name:"San Francisco 49ers",abbr:"SF",short:"49ers"},
  {name:"Seattle Seahawks",abbr:"SEA",short:"Seahawks"},
  {name:"Tampa Bay Buccaneers",abbr:"TB",short:"Buccaneers"},
  {name:"Tennessee Titans",abbr:"TEN",short:"Titans"},
  {name:"Washington Commanders",abbr:"WSH",short:"Commanders"},
];

export const NFL_ROSTERS = [
  // ── ARIZONA CARDINALS ──
  {name:"Jacoby Brissett",pos:"QB",teamAbbr:"ARI"},
  {name:"Gardner Minshew II",pos:"QB",teamAbbr:"ARI"},
  {name:"Carson Beck",pos:"QB",teamAbbr:"ARI"},
  {name:"Jeremiyah Love",pos:"RB",teamAbbr:"ARI"},
  {name:"Tyler Allgeier",pos:"RB",teamAbbr:"ARI"},
  {name:"Bam Knight",pos:"RB",teamAbbr:"ARI"},
  {name:"Marvin Harrison Jr.",pos:"WR",teamAbbr:"ARI"},
  {name:"Michael Wilson",pos:"WR",teamAbbr:"ARI"},
  {name:"Kendrick Bourne",pos:"WR",teamAbbr:"ARI"},
  {name:"Simi Fehoko",pos:"WR",teamAbbr:"ARI"},
  {name:"Reggie Virgil",pos:"WR",teamAbbr:"ARI"},
  {name:"Devin Duvernay",pos:"WR",teamAbbr:"ARI"},
  {name:"Trey McBride",pos:"TE",teamAbbr:"ARI"},
  {name:"Elijah Higgins",pos:"TE",teamAbbr:"ARI"},
  {name:"Chad Ryland",pos:"K",teamAbbr:"ARI"},
  {name:"Walter Nolen III",pos:"DE",teamAbbr:"ARI"},
  {name:"LJ Collier",pos:"DE",teamAbbr:"ARI"},
  {name:"Darius Robinson",pos:"DE",teamAbbr:"ARI"},
  {name:"Dante Stills",pos:"DE",teamAbbr:"ARI"},
  {name:"Roy Lopez",pos:"DT",teamAbbr:"ARI"},
  {name:"Andrew Billings",pos:"DT",teamAbbr:"ARI"},
  {name:"Zaven Collins",pos:"OLB",teamAbbr:"ARI"},
  {name:"Baron Browning",pos:"OLB",teamAbbr:"ARI"},
  {name:"Josh Sweat",pos:"OLB",teamAbbr:"ARI"},
  {name:"Mack Wilson Sr.",pos:"LB",teamAbbr:"ARI"},
  {name:"Jack Gibbens",pos:"LB",teamAbbr:"ARI"},
  {name:"Cody Simon",pos:"LB",teamAbbr:"ARI"},
  {name:"Will Johnson",pos:"CB",teamAbbr:"ARI"},
  {name:"Kei'Trel Clark",pos:"CB",teamAbbr:"ARI"},
  {name:"Denzel Burke",pos:"CB",teamAbbr:"ARI"},
  {name:"Max Melton",pos:"CB",teamAbbr:"ARI"},
  {name:"Garrett Williams",pos:"CB",teamAbbr:"ARI"},
  {name:"Budda Baker",pos:"S",teamAbbr:"ARI"},
  {name:"Andrew Wingard",pos:"S",teamAbbr:"ARI"},
  {name:"Dadrion Taylor-Demerson",pos:"S",teamAbbr:"ARI"},

  // ── ATLANTA FALCONS ──
  {name:"Michael Penix Jr.",pos:"QB",teamAbbr:"ATL"},
  {name:"Tua Tagovailoa",pos:"QB",teamAbbr:"ATL"},
  {name:"Cooper Rush",pos:"QB",teamAbbr:"ATL"},
  {name:"Bijan Robinson",pos:"RB",teamAbbr:"ATL"},
  {name:"Brian Robinson Jr.",pos:"RB",teamAbbr:"ATL"},
  {name:"Drake London",pos:"WR",teamAbbr:"ATL"},
  {name:"Jahan Dotson",pos:"WR",teamAbbr:"ATL"},
  {name:"Olamide Zaccheaus",pos:"WR",teamAbbr:"ATL"},
  {name:"Zachariah Branch",pos:"WR",teamAbbr:"ATL"},
  {name:"Chris Blair",pos:"WR",teamAbbr:"ATL"},
  {name:"Kyle Pitts",pos:"TE",teamAbbr:"ATL"},
  {name:"Nick Folk",pos:"K",teamAbbr:"ATL"},
  {name:"Brandon Dorlus",pos:"DE",teamAbbr:"ATL"},
  {name:"Da'Shawn Hand",pos:"DE",teamAbbr:"ATL"},
  {name:"Maason Smith",pos:"DT",teamAbbr:"ATL"},
  {name:"LaCale London",pos:"DT",teamAbbr:"ATL"},
  {name:"Gervon Dexter Sr.",pos:"DT",teamAbbr:"ATL"},
  {name:"Samson Ebukam",pos:"OLB",teamAbbr:"ATL"},
  {name:"Za'Darius Smith",pos:"OLB",teamAbbr:"ATL"},
  {name:"Cameron Thomas",pos:"OLB",teamAbbr:"ATL"},
  {name:"Christian Harris",pos:"ILB",teamAbbr:"ATL"},
  {name:"Divine Deablo",pos:"ILB",teamAbbr:"ATL"},
  {name:"AJ Terrell Jr.",pos:"CB",teamAbbr:"ATL"},
  {name:"Mike Hughes",pos:"CB",teamAbbr:"ATL"},
  {name:"CJ Henderson",pos:"CB",teamAbbr:"ATL"},
  {name:"Billy Bowman Jr.",pos:"CB",teamAbbr:"ATL"},
  {name:"Jessie Bates III",pos:"S",teamAbbr:"ATL"},
  {name:"Xavier Watts",pos:"S",teamAbbr:"ATL"},
  {name:"Sydney Brown",pos:"S",teamAbbr:"ATL"},
  {name:"DeMarcco Hellams",pos:"S",teamAbbr:"ATL"},

  // ── BALTIMORE RAVENS ──
  {name:"Lamar Jackson",pos:"QB",teamAbbr:"BAL"},
  {name:"Tyler Huntley",pos:"QB",teamAbbr:"BAL"},
  {name:"Derrick Henry",pos:"RB",teamAbbr:"BAL"},
  {name:"Justice Hill",pos:"RB",teamAbbr:"BAL"},
  {name:"Rasheen Ali",pos:"RB",teamAbbr:"BAL"},
  {name:"Zay Flowers",pos:"WR",teamAbbr:"BAL"},
  {name:"Devontez Walker",pos:"WR",teamAbbr:"BAL"},
  {name:"Rashod Bateman",pos:"WR",teamAbbr:"BAL"},
  {name:"LaJohntay Wester",pos:"WR",teamAbbr:"BAL"},
  {name:"Mark Andrews",pos:"TE",teamAbbr:"BAL"},
  {name:"Durham Smythe",pos:"TE",teamAbbr:"BAL"},
  {name:"Tyler Loop",pos:"K",teamAbbr:"BAL"},
  {name:"Nnamdi Madubuike",pos:"DE",teamAbbr:"BAL"},
  {name:"Calais Campbell",pos:"DE",teamAbbr:"BAL"},
  {name:"Travis Jones",pos:"DT",teamAbbr:"BAL"},
  {name:"Broderick Washington Jr.",pos:"DT",teamAbbr:"BAL"},
  {name:"Tavius Robinson",pos:"OLB",teamAbbr:"BAL"},
  {name:"Trey Hendrickson",pos:"OLB",teamAbbr:"BAL"},
  {name:"Mike Green",pos:"OLB",teamAbbr:"BAL"},
  {name:"Roquan Smith",pos:"LB",teamAbbr:"BAL"},
  {name:"Teddye Buchanan",pos:"LB",teamAbbr:"BAL"},
  {name:"Trenton Simpson",pos:"LB",teamAbbr:"BAL"},
  {name:"Nate Wiggins",pos:"CB",teamAbbr:"BAL"},
  {name:"TJ Tampa Jr.",pos:"CB",teamAbbr:"BAL"},
  {name:"Chidobe Awuzie",pos:"CB",teamAbbr:"BAL"},
  {name:"Marlon Humphrey",pos:"CB",teamAbbr:"BAL"},
  {name:"Kyle Hamilton",pos:"S",teamAbbr:"BAL"},
  {name:"Malaki Starks",pos:"S",teamAbbr:"BAL"},
  {name:"Jaylinn Hawkins",pos:"S",teamAbbr:"BAL"},

  // ── BUFFALO BILLS ──
  {name:"Josh Allen",pos:"QB",teamAbbr:"BUF"},
  {name:"Kyle Allen",pos:"QB",teamAbbr:"BUF"},
  {name:"James Cook III",pos:"RB",teamAbbr:"BUF"},
  {name:"Ray Davis",pos:"RB",teamAbbr:"BUF"},
  {name:"Ty Johnson",pos:"RB",teamAbbr:"BUF"},
  {name:"DJ Moore",pos:"WR",teamAbbr:"BUF"},
  {name:"Keon Coleman",pos:"WR",teamAbbr:"BUF"},
  {name:"Khalil Shakir",pos:"WR",teamAbbr:"BUF"},
  {name:"Joshua Palmer",pos:"WR",teamAbbr:"BUF"},
  {name:"Skyler Bell",pos:"WR",teamAbbr:"BUF"},
  {name:"Dalton Kincaid",pos:"TE",teamAbbr:"BUF"},
  {name:"Dawson Knox",pos:"TE",teamAbbr:"BUF"},
  {name:"Tyler Bass",pos:"K",teamAbbr:"BUF"},
  {name:"TJ Sanders",pos:"DE",teamAbbr:"BUF"},
  {name:"Landon Jackson",pos:"DE",teamAbbr:"BUF"},
  {name:"Greg Rousseau",pos:"OLB",teamAbbr:"BUF"},
  {name:"Michael Hoecht",pos:"OLB",teamAbbr:"BUF"},
  {name:"Javon Solomon",pos:"OLB",teamAbbr:"BUF"},
  {name:"Bradley Chubb",pos:"OLB",teamAbbr:"BUF"},
  {name:"TJ Parker",pos:"OLB",teamAbbr:"BUF"},
  {name:"Ed Oliver",pos:"DT",teamAbbr:"BUF"},
  {name:"Deone Walker",pos:"DT",teamAbbr:"BUF"},
  {name:"Greg Gaines",pos:"DT",teamAbbr:"BUF"},
  {name:"Terrel Bernard",pos:"LB",teamAbbr:"BUF"},
  {name:"Dorian Williams",pos:"LB",teamAbbr:"BUF"},
  {name:"Maxwell Hairston",pos:"CB",teamAbbr:"BUF"},
  {name:"Davison Igbinosun",pos:"CB",teamAbbr:"BUF"},
  {name:"Christian Benford",pos:"CB",teamAbbr:"BUF"},
  {name:"Dee Alford",pos:"CB",teamAbbr:"BUF"},
  {name:"Cole Bishop",pos:"S",teamAbbr:"BUF"},
  {name:"CJ Gardner-Johnson",pos:"S",teamAbbr:"BUF"},
  {name:"Damar Hamlin",pos:"S",teamAbbr:"BUF"},
  {name:"Sam Franklin Jr.",pos:"S",teamAbbr:"BUF"},

  // ── CAROLINA PANTHERS ──
  {name:"Bryce Young",pos:"QB",teamAbbr:"CAR"},
  {name:"Kenny Pickett",pos:"QB",teamAbbr:"CAR"},
  {name:"Chuba Hubbard",pos:"RB",teamAbbr:"CAR"},
  {name:"Jonathon Brooks",pos:"RB",teamAbbr:"CAR"},
  {name:"AJ Dillon",pos:"RB",teamAbbr:"CAR"},
  {name:"Tetairoa McMillan",pos:"WR",teamAbbr:"CAR"},
  {name:"Xavier Legette",pos:"WR",teamAbbr:"CAR"},
  {name:"Jalen Coker",pos:"WR",teamAbbr:"CAR"},
  {name:"Brycen Tremayne",pos:"WR",teamAbbr:"CAR"},
  {name:"Jimmy Horn Jr.",pos:"WR",teamAbbr:"CAR"},
  {name:"Tommy Tremble",pos:"TE",teamAbbr:"CAR"},
  {name:"Darren Waller",pos:"TE",teamAbbr:"CAR"},
  {name:"Ryan Fitzgerald",pos:"K",teamAbbr:"CAR"},
  {name:"Derrick Brown",pos:"DT",teamAbbr:"CAR"},
  {name:"Princely Umanmielen",pos:"OLB",teamAbbr:"CAR"},
  {name:"Jaelan Phillips",pos:"OLB",teamAbbr:"CAR"},
  {name:"Patrick Jones II",pos:"OLB",teamAbbr:"CAR"},
  {name:"Bobby Okereke",pos:"ILB",teamAbbr:"CAR"},
  {name:"Devin Lloyd",pos:"ILB",teamAbbr:"CAR"},
  {name:"Trevin Wallace",pos:"ILB",teamAbbr:"CAR"},
  {name:"Mike Jackson",pos:"CB",teamAbbr:"CAR"},
  {name:"Akayleb Evans",pos:"CB",teamAbbr:"CAR"},
  {name:"Tre'von Moehrig",pos:"S",teamAbbr:"CAR"},
  {name:"Lathan Ransom",pos:"S",teamAbbr:"CAR"},
  {name:"Nick Scott",pos:"S",teamAbbr:"CAR"},
  {name:"Zakee Wheatley",pos:"S",teamAbbr:"CAR"},

  // ── CHICAGO BEARS ──
  {name:"Caleb Williams",pos:"QB",teamAbbr:"CHI"},
  {name:"Tyson Bagent",pos:"QB",teamAbbr:"CHI"},
  {name:"D'Andre Swift",pos:"RB",teamAbbr:"CHI"},
  {name:"Khalil Herbert",pos:"RB",teamAbbr:"CHI"},
  {name:"Rome Odunze",pos:"WR",teamAbbr:"CHI"},
  {name:"DJ Moore",pos:"WR",teamAbbr:"CHI"},
  {name:"Keenan Allen",pos:"WR",teamAbbr:"CHI"},
  {name:"Olamide Zaccheaus",pos:"WR",teamAbbr:"CHI"},
  {name:"Cole Kmet",pos:"TE",teamAbbr:"CHI"},
  {name:"Cairo Santos",pos:"K",teamAbbr:"CHI"},
  {name:"Montez Sweat",pos:"DE",teamAbbr:"CHI"},
  {name:"Dominique Robinson",pos:"DE",teamAbbr:"CHI"},
  {name:"Gervon Dexter",pos:"DT",teamAbbr:"CHI"},
  {name:"Andrew Billings",pos:"DT",teamAbbr:"CHI"},
  {name:"Tremaine Edmunds",pos:"LB",teamAbbr:"CHI"},
  {name:"TJ Edwards",pos:"LB",teamAbbr:"CHI"},
  {name:"Kevin Byard",pos:"S",teamAbbr:"CHI"},
  {name:"Jaquan Brisker",pos:"S",teamAbbr:"CHI"},
  {name:"Jaylon Johnson",pos:"CB",teamAbbr:"CHI"},
  {name:"Tyrique Stevenson",pos:"CB",teamAbbr:"CHI"},

  // ── CINCINNATI BENGALS ──
  {name:"Joe Burrow",pos:"QB",teamAbbr:"CIN"},
  {name:"Joe Flacco",pos:"QB",teamAbbr:"CIN"},
  {name:"Chase Brown",pos:"RB",teamAbbr:"CIN"},
  {name:"Samaje Perine",pos:"RB",teamAbbr:"CIN"},
  {name:"Tahj Brooks",pos:"RB",teamAbbr:"CIN"},
  {name:"Ja'Marr Chase",pos:"WR",teamAbbr:"CIN"},
  {name:"Tee Higgins",pos:"WR",teamAbbr:"CIN"},
  {name:"Andrei Iosivas",pos:"WR",teamAbbr:"CIN"},
  {name:"Mitchell Tinsley",pos:"WR",teamAbbr:"CIN"},
  {name:"Dohnte Meyers",pos:"WR",teamAbbr:"CIN"},
  {name:"Evan McPherson",pos:"K",teamAbbr:"CIN"},
  {name:"Trey Hendrickson",pos:"DE",teamAbbr:"CIN"},
  {name:"Sam Hubbard",pos:"DE",teamAbbr:"CIN"},
  {name:"Dexter Lawrence",pos:"DT",teamAbbr:"CIN"},
  {name:"BJ Hill",pos:"DT",teamAbbr:"CIN"},
  {name:"Logan Wilson",pos:"LB",teamAbbr:"CIN"},
  {name:"Germaine Pratt",pos:"LB",teamAbbr:"CIN"},
  {name:"Joseph Ossai",pos:"LB",teamAbbr:"CIN"},
  {name:"Geno Stone",pos:"S",teamAbbr:"CIN"},
  {name:"Jordan Battle",pos:"S",teamAbbr:"CIN"},
  {name:"Cam Taylor-Britt",pos:"CB",teamAbbr:"CIN"},
  {name:"Mike Hilton",pos:"CB",teamAbbr:"CIN"},
  {name:"DJ Turner",pos:"CB",teamAbbr:"CIN"},

  // ── CLEVELAND BROWNS ──
  {name:"Deshaun Watson",pos:"QB",teamAbbr:"CLE"},
  {name:"Shedeur Sanders",pos:"QB",teamAbbr:"CLE"},
  {name:"Dillon Gabriel",pos:"QB",teamAbbr:"CLE"},
  {name:"Quinshon Judkins",pos:"RB",teamAbbr:"CLE"},
  {name:"Dylan Sampson",pos:"RB",teamAbbr:"CLE"},
  {name:"Raheim Sanders",pos:"RB",teamAbbr:"CLE"},
  {name:"Jerry Jeudy",pos:"WR",teamAbbr:"CLE"},
  {name:"Cedric Tillman",pos:"WR",teamAbbr:"CLE"},
  {name:"David Njoku",pos:"TE",teamAbbr:"CLE"},
  {name:"Andre Szmyt",pos:"K",teamAbbr:"CLE"},
  {name:"Myles Garrett",pos:"DE",teamAbbr:"CLE"},
  {name:"Za'Darius Smith",pos:"DE",teamAbbr:"CLE"},
  {name:"Dalvin Tomlinson",pos:"DT",teamAbbr:"CLE"},
  {name:"Jeremiah Owusu-Koramoah",pos:"LB",teamAbbr:"CLE"},
  {name:"Jordan Hicks",pos:"LB",teamAbbr:"CLE"},
  {name:"Grant Delpit",pos:"S",teamAbbr:"CLE"},
  {name:"Ronnie Hickman",pos:"S",teamAbbr:"CLE"},
  {name:"Denzel Ward",pos:"CB",teamAbbr:"CLE"},
  {name:"Greg Newsome II",pos:"CB",teamAbbr:"CLE"},
  {name:"Martin Emerson Jr.",pos:"CB",teamAbbr:"CLE"},

  // ── DALLAS COWBOYS ──
  {name:"Dak Prescott",pos:"QB",teamAbbr:"DAL"},
  {name:"Sam Howell",pos:"QB",teamAbbr:"DAL"},
  {name:"Javonte Williams",pos:"RB",teamAbbr:"DAL"},
  {name:"Malik Davis",pos:"RB",teamAbbr:"DAL"},
  {name:"Emari Demercado",pos:"RB",teamAbbr:"DAL"},
  {name:"CeeDee Lamb",pos:"WR",teamAbbr:"DAL"},
  {name:"George Pickens",pos:"WR",teamAbbr:"DAL"},
  {name:"Ryan Flournoy",pos:"WR",teamAbbr:"DAL"},
  {name:"KaVontae Turpin",pos:"WR",teamAbbr:"DAL"},
  {name:"Jonathan Mingo",pos:"WR",teamAbbr:"DAL"},
  {name:"Jake Ferguson",pos:"TE",teamAbbr:"DAL"},
  {name:"Brandon Aubrey",pos:"K",teamAbbr:"DAL"},
  {name:"Donovan Ezeiruaku",pos:"DE",teamAbbr:"DAL"},
  {name:"DeMarcus Lawrence",pos:"DE",teamAbbr:"DAL"},
  {name:"Quinnen Williams",pos:"DT",teamAbbr:"DAL"},
  {name:"Kenny Clark",pos:"DT",teamAbbr:"DAL"},
  {name:"DeMarvion Overshown",pos:"LB",teamAbbr:"DAL"},
  {name:"Dee Winters",pos:"LB",teamAbbr:"DAL"},
  {name:"Jalen Thompson",pos:"S",teamAbbr:"DAL"},
  {name:"Caleb Downs",pos:"S",teamAbbr:"DAL"},
  {name:"Malik Hooker",pos:"S",teamAbbr:"DAL"},
  {name:"DaRon Bland",pos:"CB",teamAbbr:"DAL"},
  {name:"Cobie Durant",pos:"CB",teamAbbr:"DAL"},
  {name:"Shavon Revel Jr.",pos:"CB",teamAbbr:"DAL"},

  // ── DENVER BRONCOS ──
  {name:"Bo Nix",pos:"QB",teamAbbr:"DEN"},
  {name:"Zach Wilson",pos:"QB",teamAbbr:"DEN"},
  {name:"JK Dobbins",pos:"RB",teamAbbr:"DEN"},
  {name:"Jonah Coleman",pos:"RB",teamAbbr:"DEN"},
  {name:"RJ Harvey",pos:"RB",teamAbbr:"DEN"},
  {name:"Jaleel McLaughlin",pos:"RB",teamAbbr:"DEN"},
  {name:"Jaylen Waddle",pos:"WR",teamAbbr:"DEN"},
  {name:"Courtland Sutton",pos:"WR",teamAbbr:"DEN"},
  {name:"Marvin Mims Jr.",pos:"WR",teamAbbr:"DEN"},
  {name:"Troy Franklin",pos:"WR",teamAbbr:"DEN"},
  {name:"Pat Bryant",pos:"WR",teamAbbr:"DEN"},
  {name:"Wil Lutz",pos:"K",teamAbbr:"DEN"},
  {name:"Nik Bonitto",pos:"OLB",teamAbbr:"DEN"},
  {name:"Jonathon Cooper",pos:"DE",teamAbbr:"DEN"},
  {name:"Zach Allen",pos:"DE",teamAbbr:"DEN"},
  {name:"Malcolm Roach",pos:"DT",teamAbbr:"DEN"},
  {name:"Alex Singleton",pos:"LB",teamAbbr:"DEN"},
  {name:"Justin Strnad",pos:"LB",teamAbbr:"DEN"},
  {name:"Pat Surtain II",pos:"CB",teamAbbr:"DEN"},
  {name:"Riley Moss",pos:"CB",teamAbbr:"DEN"},
  {name:"Jahdae Barron",pos:"CB",teamAbbr:"DEN"},
  {name:"Ja'Quan McMillian",pos:"CB",teamAbbr:"DEN"},
  {name:"Talanoa Hufanga",pos:"S",teamAbbr:"DEN"},
  {name:"Brandon Jones",pos:"S",teamAbbr:"DEN"},
  {name:"Taylor Rapp",pos:"S",teamAbbr:"DEN"},

  // ── DETROIT LIONS ──
  {name:"Jared Goff",pos:"QB",teamAbbr:"DET"},
  {name:"Hendon Hooker",pos:"QB",teamAbbr:"DET"},
  {name:"David Montgomery",pos:"RB",teamAbbr:"DET"},
  {name:"Jahmyr Gibbs",pos:"RB",teamAbbr:"DET"},
  {name:"Amon-Ra St. Brown",pos:"WR",teamAbbr:"DET"},
  {name:"Jameson Williams",pos:"WR",teamAbbr:"DET"},
  {name:"Tim Patrick",pos:"WR",teamAbbr:"DET"},
  {name:"Sam LaPorta",pos:"TE",teamAbbr:"DET"},
  {name:"Jake Bates",pos:"K",teamAbbr:"DET"},
  {name:"Aidan Hutchinson",pos:"DE",teamAbbr:"DET"},
  {name:"Marcus Davenport",pos:"DE",teamAbbr:"DET"},
  {name:"Alim McNeill",pos:"DT",teamAbbr:"DET"},
  {name:"DJ Reader",pos:"DT",teamAbbr:"DET"},
  {name:"Alex Anzalone",pos:"LB",teamAbbr:"DET"},
  {name:"Malcolm Rodriguez",pos:"LB",teamAbbr:"DET"},
  {name:"James Houston",pos:"LB",teamAbbr:"DET"},
  {name:"Kerby Joseph",pos:"S",teamAbbr:"DET"},
  {name:"Brian Branch",pos:"S",teamAbbr:"DET"},
  {name:"Carlton Davis",pos:"CB",teamAbbr:"DET"},
  {name:"Terrion Arnold",pos:"CB",teamAbbr:"DET"},

  // ── GREEN BAY PACKERS ──
  {name:"Jordan Love",pos:"QB",teamAbbr:"GB"},
  {name:"Tyrod Taylor",pos:"QB",teamAbbr:"GB"},
  {name:"Josh Jacobs",pos:"RB",teamAbbr:"GB"},
  {name:"Kaleb Johnson",pos:"RB",teamAbbr:"GB"},
  {name:"Emanuel Wilson",pos:"RB",teamAbbr:"GB"},
  {name:"Christian Watson",pos:"WR",teamAbbr:"GB"},
  {name:"Jayden Reed",pos:"WR",teamAbbr:"GB"},
  {name:"Matthew Golden",pos:"WR",teamAbbr:"GB"},
  {name:"Skyy Moore",pos:"WR",teamAbbr:"GB"},
  {name:"Savion Williams",pos:"WR",teamAbbr:"GB"},
  {name:"Tucker Kraft",pos:"TE",teamAbbr:"GB"},
  {name:"Luke Musgrave",pos:"TE",teamAbbr:"GB"},
  {name:"Trey Smack",pos:"K",teamAbbr:"GB"},
  {name:"Rashan Gary",pos:"OLB",teamAbbr:"GB"},
  {name:"Lukas Van Ness",pos:"OLB",teamAbbr:"GB"},
  {name:"Preston Smith",pos:"OLB",teamAbbr:"GB"},
  {name:"Javon Hargrave",pos:"DT",teamAbbr:"GB"},
  {name:"Kenny Clark",pos:"DT",teamAbbr:"GB"},
  {name:"Zaire Franklin",pos:"LB",teamAbbr:"GB"},
  {name:"Isaiah McDuffie",pos:"LB",teamAbbr:"GB"},
  {name:"Xavier McKinney",pos:"S",teamAbbr:"GB"},
  {name:"Evan Williams",pos:"S",teamAbbr:"GB"},
  {name:"Jaire Alexander",pos:"CB",teamAbbr:"GB"},
  {name:"Carrington Valentine",pos:"CB",teamAbbr:"GB"},

  // ── HOUSTON TEXANS ──
  {name:"CJ Stroud",pos:"QB",teamAbbr:"HOU"},
  {name:"Case Keenum",pos:"QB",teamAbbr:"HOU"},
  {name:"David Montgomery",pos:"RB",teamAbbr:"HOU"},
  {name:"Dameon Pierce",pos:"RB",teamAbbr:"HOU"},
  {name:"Nico Collins",pos:"WR",teamAbbr:"HOU"},
  {name:"Tank Dell",pos:"WR",teamAbbr:"HOU"},
  {name:"Xavier Hutchinson",pos:"WR",teamAbbr:"HOU"},
  {name:"Jaylin Noel",pos:"WR",teamAbbr:"HOU"},
  {name:"Justin Watson",pos:"WR",teamAbbr:"HOU"},
  {name:"Dalton Schultz",pos:"TE",teamAbbr:"HOU"},
  {name:"Cade Stover",pos:"TE",teamAbbr:"HOU"},
  {name:"Foster Moreau",pos:"TE",teamAbbr:"HOU"},
  {name:"Ka'imi Fairbairn",pos:"K",teamAbbr:"HOU"},
  {name:"Will Anderson Jr.",pos:"DE",teamAbbr:"HOU"},
  {name:"Danielle Hunter",pos:"DE",teamAbbr:"HOU"},
  {name:"Dylan Horton",pos:"DE",teamAbbr:"HOU"},
  {name:"Jadeveon Clowney",pos:"DE",teamAbbr:"HOU"},
  {name:"Sheldon Rankins",pos:"DT",teamAbbr:"HOU"},
  {name:"Tommy Togiai",pos:"DT",teamAbbr:"HOU"},
  {name:"Logan Hall",pos:"DT",teamAbbr:"HOU"},
  {name:"Jalen Pitre",pos:"S",teamAbbr:"HOU"},
  {name:"Jimmie Ward",pos:"S",teamAbbr:"HOU"},
  {name:"Derek Stingley Jr.",pos:"CB",teamAbbr:"HOU"},
  {name:"Kamari Lassiter",pos:"CB",teamAbbr:"HOU"},

  // ── INDIANAPOLIS COLTS ──
  {name:"Daniel Jones",pos:"QB",teamAbbr:"IND"},
  {name:"Anthony Richardson",pos:"QB",teamAbbr:"IND"},
  {name:"Jonathan Taylor",pos:"RB",teamAbbr:"IND"},
  {name:"Seth McGowan",pos:"RB",teamAbbr:"IND"},
  {name:"Ulysses Bentley IV",pos:"RB",teamAbbr:"IND"},
  {name:"Alec Pierce",pos:"WR",teamAbbr:"IND"},
  {name:"Josh Downs",pos:"WR",teamAbbr:"IND"},
  {name:"Keenan Allen",pos:"WR",teamAbbr:"IND"},
  {name:"Nick Westbrook-Ikhine",pos:"WR",teamAbbr:"IND"},
  {name:"Tyler Warren",pos:"TE",teamAbbr:"IND"},
  {name:"Mo Alie-Cox",pos:"TE",teamAbbr:"IND"},
  {name:"Spencer Shrader",pos:"K",teamAbbr:"IND"},
  {name:"Laiatu Latu",pos:"DE",teamAbbr:"IND"},
  {name:"Arden Key",pos:"DE",teamAbbr:"IND"},
  {name:"DeForest Buckner",pos:"DT",teamAbbr:"IND"},
  {name:"Grover Stewart",pos:"DT",teamAbbr:"IND"},
  {name:"Akeem Davis-Gaither",pos:"LB",teamAbbr:"IND"},
  {name:"CJ Allen",pos:"LB",teamAbbr:"IND"},
  {name:"Austin Ajiake",pos:"LB",teamAbbr:"IND"},
  {name:"Sauce Gardner",pos:"CB",teamAbbr:"IND"},
  {name:"JuJu Brents",pos:"CB",teamAbbr:"IND"},
  {name:"Charvarius Ward",pos:"CB",teamAbbr:"IND"},

  // ── JACKSONVILLE JAGUARS ──
  {name:"Trevor Lawrence",pos:"QB",teamAbbr:"JAX"},
  {name:"Mac Jones",pos:"QB",teamAbbr:"JAX"},
  {name:"Bhayshul Tuten",pos:"RB",teamAbbr:"JAX"},
  {name:"Tank Bigsby",pos:"RB",teamAbbr:"JAX"},
  {name:"Travis Hunter",pos:"WR",teamAbbr:"JAX"},
  {name:"Jakobi Meyers",pos:"WR",teamAbbr:"JAX"},
  {name:"Brian Thomas Jr.",pos:"WR",teamAbbr:"JAX"},
  {name:"Parker Washington",pos:"WR",teamAbbr:"JAX"},
  {name:"Josh Cameron",pos:"WR",teamAbbr:"JAX"},
  {name:"Evan Engram",pos:"TE",teamAbbr:"JAX"},
  {name:"Cam Little",pos:"K",teamAbbr:"JAX"},
  {name:"Josh Hines-Allen",pos:"OLB",teamAbbr:"JAX"},
  {name:"Travon Walker",pos:"DE",teamAbbr:"JAX"},
  {name:"BJ Green II",pos:"DE",teamAbbr:"JAX"},
  {name:"DaVon Hamilton",pos:"DT",teamAbbr:"JAX"},
  {name:"Arik Armstead",pos:"DT",teamAbbr:"JAX"},
  {name:"Ruke Orhorhoro",pos:"DT",teamAbbr:"JAX"},
  {name:"Foyesade Oluokun",pos:"LB",teamAbbr:"JAX"},
  {name:"Devin Lloyd",pos:"LB",teamAbbr:"JAX"},
  {name:"Andre Cisco",pos:"S",teamAbbr:"JAX"},
  {name:"Daniel Thomas",pos:"S",teamAbbr:"JAX"},
  {name:"Tyson Campbell",pos:"CB",teamAbbr:"JAX"},
  {name:"Ronald Darby",pos:"CB",teamAbbr:"JAX"},

  // ── KANSAS CITY CHIEFS ──
  {name:"Patrick Mahomes",pos:"QB",teamAbbr:"KC"},
  {name:"Garrett Nussmeier",pos:"QB",teamAbbr:"KC"},
  {name:"Kenneth Walker III",pos:"RB",teamAbbr:"KC"},
  {name:"Jaydn Ott",pos:"RB",teamAbbr:"KC"},
  {name:"Brashard Smith",pos:"RB",teamAbbr:"KC"},
  {name:"Rashee Rice",pos:"WR",teamAbbr:"KC"},
  {name:"Jalen Royals",pos:"WR",teamAbbr:"KC"},
  {name:"Xavier Worthy",pos:"WR",teamAbbr:"KC"},
  {name:"Travis Kelce",pos:"TE",teamAbbr:"KC"},
  {name:"Noah Gray",pos:"TE",teamAbbr:"KC"},
  {name:"Harrison Butker",pos:"K",teamAbbr:"KC"},
  {name:"George Karlaftis",pos:"DE",teamAbbr:"KC"},
  {name:"Felix Anudike-Uzomah",pos:"DE",teamAbbr:"KC"},
  {name:"Emmanuel Ogbah",pos:"DE",teamAbbr:"KC"},
  {name:"Ashton Gillotte",pos:"DE",teamAbbr:"KC"},
  {name:"Chris Jones",pos:"DT",teamAbbr:"KC"},
  {name:"Khyiris Tonga",pos:"DT",teamAbbr:"KC"},
  {name:"Omarr Norman-Lott",pos:"DT",teamAbbr:"KC"},
  {name:"Nick Bolton",pos:"LB",teamAbbr:"KC"},
  {name:"Drue Tranquill",pos:"LB",teamAbbr:"KC"},
  {name:"Kristian Fulton",pos:"CB",teamAbbr:"KC"},
  {name:"Kader Kohou",pos:"CB",teamAbbr:"KC"},
  {name:"Chamarri Conner",pos:"S",teamAbbr:"KC"},
  {name:"DeShon Singleton",pos:"S",teamAbbr:"KC"},
  {name:"Alohi Gilman",pos:"S",teamAbbr:"KC"},

  // ── LAS VEGAS RAIDERS ──
  {name:"Ashton Jeanty",pos:"RB",teamAbbr:"LV"},
  {name:"Mike Washington Jr.",pos:"RB",teamAbbr:"LV"},
  {name:"Roman Hemby",pos:"RB",teamAbbr:"LV"},
  {name:"Dylan Laube",pos:"RB",teamAbbr:"LV"},
  {name:"Brock Bowers",pos:"TE",teamAbbr:"LV"},
  {name:"Matt Gay",pos:"K",teamAbbr:"LV"},
  {name:"Maxx Crosby",pos:"DE",teamAbbr:"LV"},
  {name:"Malcolm Koonce",pos:"DE",teamAbbr:"LV"},
  {name:"Adam Butler",pos:"DT",teamAbbr:"LV"},
  {name:"Robert Spillane",pos:"LB",teamAbbr:"LV"},
  {name:"Divine Deablo",pos:"LB",teamAbbr:"LV"},
  {name:"Marcus Epps",pos:"S",teamAbbr:"LV"},
  {name:"Nate Hobbs",pos:"CB",teamAbbr:"LV"},

  // ── LOS ANGELES CHARGERS ──
  {name:"Justin Herbert",pos:"QB",teamAbbr:"LAC"},
  {name:"Easton Stick",pos:"QB",teamAbbr:"LAC"},
  {name:"Gus Edwards",pos:"RB",teamAbbr:"LAC"},
  {name:"Kimani Vidal",pos:"RB",teamAbbr:"LAC"},
  {name:"Quentin Johnston",pos:"WR",teamAbbr:"LAC"},
  {name:"Ladd McConkey",pos:"WR",teamAbbr:"LAC"},
  {name:"Joshua Palmer",pos:"WR",teamAbbr:"LAC"},
  {name:"Will Dissly",pos:"TE",teamAbbr:"LAC"},
  {name:"Cameron Dicker",pos:"K",teamAbbr:"LAC"},
  {name:"Khalil Mack",pos:"OLB",teamAbbr:"LAC"},
  {name:"Joey Bosa",pos:"DE",teamAbbr:"LAC"},
  {name:"Morgan Fox",pos:"DE",teamAbbr:"LAC"},
  {name:"Sebastian Joseph-Day",pos:"DT",teamAbbr:"LAC"},
  {name:"Daiyan Henley",pos:"LB",teamAbbr:"LAC"},
  {name:"Eric Kendricks",pos:"LB",teamAbbr:"LAC"},
  {name:"Derwin James",pos:"S",teamAbbr:"LAC"},
  {name:"Alohi Gilman",pos:"S",teamAbbr:"LAC"},
  {name:"Asante Samuel Jr.",pos:"CB",teamAbbr:"LAC"},
  {name:"Kristian Fulton",pos:"CB",teamAbbr:"LAC"},

  // ── LOS ANGELES RAMS ──
  {name:"Matthew Stafford",pos:"QB",teamAbbr:"LAR"},
  {name:"Stetson Bennett IV",pos:"QB",teamAbbr:"LAR"},
  {name:"Kyren Williams",pos:"RB",teamAbbr:"LAR"},
  {name:"Blake Corum",pos:"RB",teamAbbr:"LAR"},
  {name:"Ronnie Rivers",pos:"RB",teamAbbr:"LAR"},
  {name:"Davante Adams",pos:"WR",teamAbbr:"LAR"},
  {name:"Puka Nacua",pos:"WR",teamAbbr:"LAR"},
  {name:"Jordan Whittington",pos:"WR",teamAbbr:"LAR"},
  {name:"Konata Mumpfield",pos:"WR",teamAbbr:"LAR"},
  {name:"Tyler Higbee",pos:"TE",teamAbbr:"LAR"},
  {name:"Harrison Mevis",pos:"K",teamAbbr:"LAR"},
  {name:"Myles Garrett",pos:"DE",teamAbbr:"LAR"},
  {name:"Braden Fiske",pos:"DT",teamAbbr:"LAR"},
  {name:"Kobie Turner",pos:"DT",teamAbbr:"LAR"},
  {name:"Osa Odighizuwa",pos:"DT",teamAbbr:"LAR"},
  {name:"Rashan Gary",pos:"OLB",teamAbbr:"LAR"},
  {name:"Ernest Jones IV",pos:"LB",teamAbbr:"LAR"},
  {name:"Christian Rozeboom",pos:"LB",teamAbbr:"LAR"},
  {name:"Kamren Curl",pos:"S",teamAbbr:"LAR"},
  {name:"Quindell Johnson",pos:"S",teamAbbr:"LAR"},
  {name:"Tre'Davious White",pos:"CB",teamAbbr:"LAR"},
  {name:"Darious Williams",pos:"CB",teamAbbr:"LAR"},

  // ── MIAMI DOLPHINS ──
  {name:"Tua Tagovailoa",pos:"QB",teamAbbr:"MIA"},
  {name:"Tyler Huntley",pos:"QB",teamAbbr:"MIA"},
  {name:"De'Von Achane",pos:"RB",teamAbbr:"MIA"},
  {name:"Raheem Mostert",pos:"RB",teamAbbr:"MIA"},
  {name:"Tyreek Hill",pos:"WR",teamAbbr:"MIA"},
  {name:"Jaylen Waddle",pos:"WR",teamAbbr:"MIA"},
  {name:"Braxton Berrios",pos:"WR",teamAbbr:"MIA"},
  {name:"Durham Smythe",pos:"TE",teamAbbr:"MIA"},
  {name:"Riley Patterson",pos:"K",teamAbbr:"MIA"},
  {name:"Jaelan Phillips",pos:"DE",teamAbbr:"MIA"},
  {name:"Emmanuel Ogbah",pos:"DE",teamAbbr:"MIA"},
  {name:"Zach Sieler",pos:"DT",teamAbbr:"MIA"},
  {name:"Christian Wilkins",pos:"DT",teamAbbr:"MIA"},
  {name:"David Long Jr.",pos:"LB",teamAbbr:"MIA"},
  {name:"Jordan Brooks",pos:"LB",teamAbbr:"MIA"},
  {name:"Jevon Holland",pos:"S",teamAbbr:"MIA"},
  {name:"DeShon Elliott",pos:"S",teamAbbr:"MIA"},
  {name:"Xavien Howard",pos:"CB",teamAbbr:"MIA"},
  {name:"Kader Kohou",pos:"CB",teamAbbr:"MIA"},

  // ── MINNESOTA VIKINGS ──
  {name:"Sam Darnold",pos:"QB",teamAbbr:"MIN"},
  {name:"Brett Rypien",pos:"QB",teamAbbr:"MIN"},
  {name:"Aaron Jones",pos:"RB",teamAbbr:"MIN"},
  {name:"Ty Chandler",pos:"RB",teamAbbr:"MIN"},
  {name:"Justin Jefferson",pos:"WR",teamAbbr:"MIN"},
  {name:"Jordan Addison",pos:"WR",teamAbbr:"MIN"},
  {name:"Jalen Nailor",pos:"WR",teamAbbr:"MIN"},
  {name:"TJ Hockenson",pos:"TE",teamAbbr:"MIN"},
  {name:"Josh Oliver",pos:"TE",teamAbbr:"MIN"},
  {name:"Will Reichard",pos:"K",teamAbbr:"MIN"},
  {name:"Jonathan Greenard",pos:"DE",teamAbbr:"MIN"},
  {name:"Andrew Van Ginkel",pos:"OLB",teamAbbr:"MIN"},
  {name:"Pat Jones II",pos:"DE",teamAbbr:"MIN"},
  {name:"Harrison Phillips",pos:"DT",teamAbbr:"MIN"},
  {name:"Javon Hargrave",pos:"DT",teamAbbr:"MIN"},
  {name:"Ivan Pace Jr.",pos:"LB",teamAbbr:"MIN"},
  {name:"Blake Cashman",pos:"LB",teamAbbr:"MIN"},
  {name:"Harrison Smith",pos:"S",teamAbbr:"MIN"},
  {name:"Josh Metellus",pos:"S",teamAbbr:"MIN"},
  {name:"Byron Murphy II",pos:"CB",teamAbbr:"MIN"},
  {name:"Stephon Gilmore",pos:"CB",teamAbbr:"MIN"},

  // ── NEW ENGLAND PATRIOTS ──
  {name:"Drake Maye",pos:"QB",teamAbbr:"NE"},
  {name:"Tommy DeVito",pos:"QB",teamAbbr:"NE"},
  {name:"Behren Morton",pos:"QB",teamAbbr:"NE"},
  {name:"Rhamondre Stevenson",pos:"RB",teamAbbr:"NE"},
  {name:"Antonio Gibson",pos:"RB",teamAbbr:"NE"},
  {name:"AJ Brown",pos:"WR",teamAbbr:"NE"},
  {name:"Romeo Doubs",pos:"WR",teamAbbr:"NE"},
  {name:"DeMario Douglas",pos:"WR",teamAbbr:"NE"},
  {name:"Mack Hollins",pos:"WR",teamAbbr:"NE"},
  {name:"Kayshon Boutte",pos:"WR",teamAbbr:"NE"},
  {name:"Kyle Williams",pos:"WR",teamAbbr:"NE"},
  {name:"Efton Chism III",pos:"WR",teamAbbr:"NE"},
  {name:"Hunter Henry",pos:"TE",teamAbbr:"NE"},
  {name:"Andy Borregales",pos:"K",teamAbbr:"NE"},
  {name:"Keion White",pos:"DE",teamAbbr:"NE"},
  {name:"Deatrich Wise Jr.",pos:"DE",teamAbbr:"NE"},
  {name:"Christian Barmore",pos:"DT",teamAbbr:"NE"},
  {name:"Davon Godchaux",pos:"DT",teamAbbr:"NE"},
  {name:"Ja'Whaun Bentley",pos:"LB",teamAbbr:"NE"},
  {name:"Raekwon McMillan",pos:"LB",teamAbbr:"NE"},
  {name:"Khalil Jacobs",pos:"LB",teamAbbr:"NE"},
  {name:"Kyle Dugger",pos:"S",teamAbbr:"NE"},
  {name:"Jabrill Peppers",pos:"S",teamAbbr:"NE"},
  {name:"Christian Gonzalez",pos:"CB",teamAbbr:"NE"},
  {name:"Jonathan Jones",pos:"CB",teamAbbr:"NE"},

  // ── NEW ORLEANS SAINTS ──
  {name:"Derek Carr",pos:"QB",teamAbbr:"NO"},
  {name:"Jake Haener",pos:"QB",teamAbbr:"NO"},
  {name:"Alvin Kamara",pos:"RB",teamAbbr:"NO"},
  {name:"Kendre Miller",pos:"RB",teamAbbr:"NO"},
  {name:"Chris Olave",pos:"WR",teamAbbr:"NO"},
  {name:"Rashid Shaheed",pos:"WR",teamAbbr:"NO"},
  {name:"Jordyn Tyson",pos:"WR",teamAbbr:"NO"},
  {name:"Foster Moreau",pos:"TE",teamAbbr:"NO"},
  {name:"Juwan Johnson",pos:"TE",teamAbbr:"NO"},
  {name:"Daniel Carlson",pos:"K",teamAbbr:"NO"},
  {name:"Cameron Jordan",pos:"DE",teamAbbr:"NO"},
  {name:"Carl Granderson",pos:"DE",teamAbbr:"NO"},
  {name:"Bryan Bresee",pos:"DT",teamAbbr:"NO"},
  {name:"Nathan Shepherd",pos:"DT",teamAbbr:"NO"},
  {name:"Demario Davis",pos:"LB",teamAbbr:"NO"},
  {name:"Pete Werner",pos:"LB",teamAbbr:"NO"},
  {name:"Tyrann Mathieu",pos:"S",teamAbbr:"NO"},
  {name:"Jordan Howden",pos:"S",teamAbbr:"NO"},
  {name:"Paulson Adebo",pos:"CB",teamAbbr:"NO"},
  {name:"Alontae Taylor",pos:"CB",teamAbbr:"NO"},

  // ── NEW YORK GIANTS ──
  {name:"Cam Skattebo",pos:"RB",teamAbbr:"NYG"},
  {name:"Tyrone Tracy Jr.",pos:"RB",teamAbbr:"NYG"},
  {name:"Devin Singletary",pos:"RB",teamAbbr:"NYG"},
  {name:"Najee Harris",pos:"RB",teamAbbr:"NYG"},
  {name:"Malik Nabers",pos:"WR",teamAbbr:"NYG"},
  {name:"Malachi Fields",pos:"WR",teamAbbr:"NYG"},
  {name:"Darnell Mooney",pos:"WR",teamAbbr:"NYG"},
  {name:"Darius Slayton",pos:"WR",teamAbbr:"NYG"},
  {name:"Calvin Austin III",pos:"WR",teamAbbr:"NYG"},
  {name:"Odell Beckham Jr.",pos:"WR",teamAbbr:"NYG"},
  {name:"Isaiah Likely",pos:"TE",teamAbbr:"NYG"},
  {name:"Theo Johnson",pos:"TE",teamAbbr:"NYG"},
  {name:"Dominic Zvada",pos:"K",teamAbbr:"NYG"},
  {name:"Kayvon Thibodeaux",pos:"DE",teamAbbr:"NYG"},
  {name:"Brian Burns",pos:"DE",teamAbbr:"NYG"},
  {name:"Dexter Lawrence",pos:"DT",teamAbbr:"NYG"},
  {name:"Tremaine Edmunds",pos:"LB",teamAbbr:"NYG"},
  {name:"Arvell Reese",pos:"LB",teamAbbr:"NYG"},
  {name:"Micah McFadden",pos:"LB",teamAbbr:"NYG"},
  {name:"Jevon Holland",pos:"S",teamAbbr:"NYG"},
  {name:"Tyler Nubin",pos:"S",teamAbbr:"NYG"},
  {name:"Greg Newsome II",pos:"CB",teamAbbr:"NYG"},
  {name:"Deonte Banks",pos:"CB",teamAbbr:"NYG"},
  {name:"Paulson Adebo",pos:"CB",teamAbbr:"NYG"},

  // ── NEW YORK JETS ──
  {name:"Aaron Rodgers",pos:"QB",teamAbbr:"NYJ"},
  {name:"Tyrod Taylor",pos:"QB",teamAbbr:"NYJ"},
  {name:"Breece Hall",pos:"RB",teamAbbr:"NYJ"},
  {name:"Braelon Allen",pos:"RB",teamAbbr:"NYJ"},
  {name:"Garrett Wilson",pos:"WR",teamAbbr:"NYJ"},
  {name:"Davante Adams",pos:"WR",teamAbbr:"NYJ"},
  {name:"Malachi Corley",pos:"WR",teamAbbr:"NYJ"},
  {name:"Allen Lazard",pos:"WR",teamAbbr:"NYJ"},
  {name:"Tyler Conklin",pos:"TE",teamAbbr:"NYJ"},
  {name:"Blake Grupe",pos:"K",teamAbbr:"NYJ"},
  {name:"Quinnen Williams",pos:"DT",teamAbbr:"NYJ"},
  {name:"Jermaine Johnson II",pos:"DE",teamAbbr:"NYJ"},
  {name:"Will McDonald IV",pos:"DE",teamAbbr:"NYJ"},
  {name:"Haason Reddick",pos:"OLB",teamAbbr:"NYJ"},
  {name:"CJ Mosley",pos:"LB",teamAbbr:"NYJ"},
  {name:"Jamien Sherwood",pos:"LB",teamAbbr:"NYJ"},
  {name:"Tony Adams",pos:"S",teamAbbr:"NYJ"},
  {name:"Jordan Whitehead",pos:"S",teamAbbr:"NYJ"},
  {name:"Sauce Gardner",pos:"CB",teamAbbr:"NYJ"},
  {name:"DJ Reed",pos:"CB",teamAbbr:"NYJ"},

  // ── PHILADELPHIA EAGLES ──
  {name:"Jalen Hurts",pos:"QB",teamAbbr:"PHI"},
  {name:"Kenny Pickett",pos:"QB",teamAbbr:"PHI"},
  {name:"Saquon Barkley",pos:"RB",teamAbbr:"PHI"},
  {name:"Kenneth Gainwell",pos:"RB",teamAbbr:"PHI"},
  {name:"DeVonta Smith",pos:"WR",teamAbbr:"PHI"},
  {name:"Makai Lemon",pos:"WR",teamAbbr:"PHI"},
  {name:"Dontayvion Wicks",pos:"WR",teamAbbr:"PHI"},
  {name:"Hollywood Brown",pos:"WR",teamAbbr:"PHI"},
  {name:"Elijah Moore",pos:"WR",teamAbbr:"PHI"},
  {name:"Dallas Goedert",pos:"TE",teamAbbr:"PHI"},
  {name:"Jake Elliott",pos:"K",teamAbbr:"PHI"},
  {name:"Jalen Carter",pos:"DT",teamAbbr:"PHI"},
  {name:"Jordan Davis",pos:"DT",teamAbbr:"PHI"},
  {name:"Josh Sweat",pos:"DE",teamAbbr:"PHI"},
  {name:"Jonathan Greenard",pos:"DE",teamAbbr:"PHI"},
  {name:"Zack Baun",pos:"LB",teamAbbr:"PHI"},
  {name:"Jihaad Campbell",pos:"LB",teamAbbr:"PHI"},
  {name:"Jeremiah Trotter Jr.",pos:"LB",teamAbbr:"PHI"},
  {name:"Jalyx Hunt",pos:"LB",teamAbbr:"PHI"},
  {name:"Nolan Smith Jr.",pos:"LB",teamAbbr:"PHI"},
  {name:"Reed Blankenship",pos:"S",teamAbbr:"PHI"},
  {name:"Sydney Brown",pos:"S",teamAbbr:"PHI"},
  {name:"Quinyon Mitchell",pos:"CB",teamAbbr:"PHI"},
  {name:"James Bradberry",pos:"CB",teamAbbr:"PHI"},
  {name:"Darius Slay",pos:"CB",teamAbbr:"PHI"},

  // ── PITTSBURGH STEELERS ──
  {name:"Aaron Rodgers",pos:"QB",teamAbbr:"PIT"},
  {name:"Russell Wilson",pos:"QB",teamAbbr:"PIT"},
  {name:"Justin Fields",pos:"QB",teamAbbr:"PIT"},
  {name:"Najee Harris",pos:"RB",teamAbbr:"PIT"},
  {name:"Jaylen Warren",pos:"RB",teamAbbr:"PIT"},
  {name:"George Pickens",pos:"WR",teamAbbr:"PIT"},
  {name:"Van Jefferson",pos:"WR",teamAbbr:"PIT"},
  {name:"Calvin Austin III",pos:"WR",teamAbbr:"PIT"},
  {name:"Pat Freiermuth",pos:"TE",teamAbbr:"PIT"},
  {name:"Chris Boswell",pos:"K",teamAbbr:"PIT"},
  {name:"TJ Watt",pos:"OLB",teamAbbr:"PIT"},
  {name:"Alex Highsmith",pos:"OLB",teamAbbr:"PIT"},
  {name:"Cameron Heyward",pos:"DT",teamAbbr:"PIT"},
  {name:"Larry Ogunjobi",pos:"DT",teamAbbr:"PIT"},
  {name:"Patrick Queen",pos:"LB",teamAbbr:"PIT"},
  {name:"Payton Wilson",pos:"LB",teamAbbr:"PIT"},
  {name:"Minkah Fitzpatrick",pos:"S",teamAbbr:"PIT"},
  {name:"DeShon Elliott",pos:"S",teamAbbr:"PIT"},
  {name:"Joey Porter Jr.",pos:"CB",teamAbbr:"PIT"},
  {name:"Donte Jackson",pos:"CB",teamAbbr:"PIT"},

  // ── SAN FRANCISCO 49ERS ──
  {name:"Brock Purdy",pos:"QB",teamAbbr:"SF"},
  {name:"Mac Jones",pos:"QB",teamAbbr:"SF"},
  {name:"Christian McCaffrey",pos:"RB",teamAbbr:"SF"},
  {name:"Jordan Mason",pos:"RB",teamAbbr:"SF"},
  {name:"Mike Evans",pos:"WR",teamAbbr:"SF"},
  {name:"Deebo Samuel Sr.",pos:"WR",teamAbbr:"SF"},
  {name:"De'Zhaun Stribling",pos:"WR",teamAbbr:"SF"},
  {name:"Demarcus Robinson",pos:"WR",teamAbbr:"SF"},
  {name:"Christian Kirk",pos:"WR",teamAbbr:"SF"},
  {name:"George Kittle",pos:"TE",teamAbbr:"SF"},
  {name:"Eddy Pineiro",pos:"K",teamAbbr:"SF"},
  {name:"Nick Bosa",pos:"DE",teamAbbr:"SF"},
  {name:"Osa Odighizuwa",pos:"DE",teamAbbr:"SF"},
  {name:"Keion White",pos:"DE",teamAbbr:"SF"},
  {name:"Alfred Collins",pos:"DT",teamAbbr:"SF"},
  {name:"CJ West",pos:"DT",teamAbbr:"SF"},
  {name:"Sam Okuayinonu",pos:"DT",teamAbbr:"SF"},
  {name:"Fred Warner",pos:"LB",teamAbbr:"SF"},
  {name:"Dre Greenlaw",pos:"LB",teamAbbr:"SF"},
  {name:"Jaden Dugger",pos:"LB",teamAbbr:"SF"},
  {name:"Ji'Ayir Brown",pos:"S",teamAbbr:"SF"},
  {name:"Malik Mustapha",pos:"S",teamAbbr:"SF"},
  {name:"Deommodore Lenoir",pos:"CB",teamAbbr:"SF"},
  {name:"Renardo Green",pos:"CB",teamAbbr:"SF"},
  {name:"Jack Jones",pos:"CB",teamAbbr:"SF"},

  // ── SEATTLE SEAHAWKS ──
  {name:"Geno Smith",pos:"QB",teamAbbr:"SEA"},
  {name:"Sam Howell",pos:"QB",teamAbbr:"SEA"},
  {name:"Kenneth Walker III",pos:"RB",teamAbbr:"SEA"},
  {name:"Zach Charbonnet",pos:"RB",teamAbbr:"SEA"},
  {name:"Jadarian Price",pos:"RB",teamAbbr:"SEA"},
  {name:"DK Metcalf",pos:"WR",teamAbbr:"SEA"},
  {name:"Tyler Lockett",pos:"WR",teamAbbr:"SEA"},
  {name:"Jaxon Smith-Njigba",pos:"WR",teamAbbr:"SEA"},
  {name:"Noah Fant",pos:"TE",teamAbbr:"SEA"},
  {name:"Jason Myers",pos:"K",teamAbbr:"SEA"},
  {name:"Leonard Williams",pos:"DT",teamAbbr:"SEA"},
  {name:"Jarran Reed",pos:"DT",teamAbbr:"SEA"},
  {name:"Boye Mafe",pos:"DE",teamAbbr:"SEA"},
  {name:"Dre'Mont Jones",pos:"DE",teamAbbr:"SEA"},
  {name:"Uchenna Nwosu",pos:"OLB",teamAbbr:"SEA"},
  {name:"Jerome Baker",pos:"LB",teamAbbr:"SEA"},
  {name:"Tyrel Dodson",pos:"LB",teamAbbr:"SEA"},
  {name:"Julian Love",pos:"S",teamAbbr:"SEA"},
  {name:"Coby Bryant",pos:"S",teamAbbr:"SEA"},
  {name:"Devon Witherspoon",pos:"CB",teamAbbr:"SEA"},
  {name:"Riq Woolen",pos:"CB",teamAbbr:"SEA"},

  // ── TAMPA BAY BUCCANEERS ──
  {name:"Baker Mayfield",pos:"QB",teamAbbr:"TB"},
  {name:"Jalon Daniels",pos:"QB",teamAbbr:"TB"},
  {name:"Jake Browning",pos:"QB",teamAbbr:"TB"},
  {name:"Rachaad White",pos:"RB",teamAbbr:"TB"},
  {name:"Sean Tucker",pos:"RB",teamAbbr:"TB"},
  {name:"Mike Evans",pos:"WR",teamAbbr:"TB"},
  {name:"Chris Godwin",pos:"WR",teamAbbr:"TB"},
  {name:"Trey Palmer",pos:"WR",teamAbbr:"TB"},
  {name:"Cade Otton",pos:"TE",teamAbbr:"TB"},
  {name:"Chase McLaughlin",pos:"K",teamAbbr:"TB"},
  {name:"Vita Vea",pos:"DT",teamAbbr:"TB"},
  {name:"Greg Gaines",pos:"DT",teamAbbr:"TB"},
  {name:"William Gholston",pos:"DE",teamAbbr:"TB"},
  {name:"Yaya Diaby",pos:"OLB",teamAbbr:"TB"},
  {name:"Lavonte David",pos:"LB",teamAbbr:"TB"},
  {name:"SirVocea Dennis",pos:"LB",teamAbbr:"TB"},
  {name:"Antoine Winfield Jr.",pos:"S",teamAbbr:"TB"},
  {name:"Jordan Whitehead",pos:"S",teamAbbr:"TB"},
  {name:"Jamel Dean",pos:"CB",teamAbbr:"TB"},
  {name:"Zyon McCollum",pos:"CB",teamAbbr:"TB"},

  // ── TENNESSEE TITANS ──
  {name:"Cam Ward",pos:"QB",teamAbbr:"TEN"},
  {name:"Will Levis",pos:"QB",teamAbbr:"TEN"},
  {name:"Tony Pollard",pos:"RB",teamAbbr:"TEN"},
  {name:"Tyjae Spears",pos:"RB",teamAbbr:"TEN"},
  {name:"Calvin Ridley",pos:"WR",teamAbbr:"TEN"},
  {name:"Wan'Dale Robinson",pos:"WR",teamAbbr:"TEN"},
  {name:"Carnell Tate",pos:"WR",teamAbbr:"TEN"},
  {name:"Chimere Dike",pos:"WR",teamAbbr:"TEN"},
  {name:"Elic Ayomanor",pos:"WR",teamAbbr:"TEN"},
  {name:"Chigoziem Okonkwo",pos:"TE",teamAbbr:"TEN"},
  {name:"Joey Slye",pos:"K",teamAbbr:"TEN"},
  {name:"Harold Landry III",pos:"OLB",teamAbbr:"TEN"},
  {name:"John Franklin-Myers",pos:"DE",teamAbbr:"TEN"},
  {name:"Jeffery Simmons",pos:"DT",teamAbbr:"TEN"},
  {name:"Sebastian Joseph-Day",pos:"DT",teamAbbr:"TEN"},
  {name:"Jack Gibbens",pos:"LB",teamAbbr:"TEN"},
  {name:"Azeez Al-Shaair",pos:"LB",teamAbbr:"TEN"},
  {name:"Quandre Diggs",pos:"S",teamAbbr:"TEN"},
  {name:"Amani Hooker",pos:"S",teamAbbr:"TEN"},
  {name:"Roger McCreary",pos:"CB",teamAbbr:"TEN"},
  {name:"Darrell Baker Jr.",pos:"CB",teamAbbr:"TEN"},
  {name:"L'Jarius Sneed",pos:"CB",teamAbbr:"TEN"},

  // ── WASHINGTON COMMANDERS ──
  {name:"Jayden Daniels",pos:"QB",teamAbbr:"WSH"},
  {name:"Marcus Mariota",pos:"QB",teamAbbr:"WSH"},
  {name:"Athan Kaliakmanis",pos:"QB",teamAbbr:"WSH"},
  {name:"Rachaad White",pos:"RB",teamAbbr:"WSH"},
  {name:"Jacory Croskey-Merritt",pos:"RB",teamAbbr:"WSH"},
  {name:"Kaytron Allen",pos:"RB",teamAbbr:"WSH"},
  {name:"Terry McLaurin",pos:"WR",teamAbbr:"WSH"},
  {name:"Stefon Diggs",pos:"WR",teamAbbr:"WSH"},
  {name:"Antonio Williams",pos:"WR",teamAbbr:"WSH"},
  {name:"Treylon Burks",pos:"WR",teamAbbr:"WSH"},
  {name:"Luke McCaffrey",pos:"WR",teamAbbr:"WSH"},
  {name:"Dyami Brown",pos:"WR",teamAbbr:"WSH"},
  {name:"Chig Okonkwo",pos:"TE",teamAbbr:"WSH"},
  {name:"Ben Sinnott",pos:"TE",teamAbbr:"WSH"},
  {name:"Drew Stevens",pos:"K",teamAbbr:"WSH"},
  {name:"Daron Payne",pos:"DT",teamAbbr:"WSH"},
  {name:"Javon Kinlaw",pos:"DT",teamAbbr:"WSH"},
  {name:"Tim Settle",pos:"DT",teamAbbr:"WSH"},
  {name:"Charles Omenihu",pos:"DE",teamAbbr:"WSH"},
  {name:"Odafe Oweh",pos:"DE",teamAbbr:"WSH"},
  {name:"K'Lavon Chaisson",pos:"OLB",teamAbbr:"WSH"},
  {name:"Frankie Luvu",pos:"LB",teamAbbr:"WSH"},
  {name:"Leo Chenal",pos:"LB",teamAbbr:"WSH"},
  {name:"Sonny Styles",pos:"LB",teamAbbr:"WSH"},
  {name:"Javontae Jean-Baptiste",pos:"LB",teamAbbr:"WSH"},
  {name:"Nick Cross",pos:"S",teamAbbr:"WSH"},
  {name:"Percy Butler",pos:"S",teamAbbr:"WSH"},
  {name:"Quan Martin",pos:"S",teamAbbr:"WSH"},
  {name:"Trey Amos",pos:"CB",teamAbbr:"WSH"},
  {name:"Mike Sainristil",pos:"CB",teamAbbr:"WSH"},
  {name:"Rasul Douglas",pos:"CB",teamAbbr:"WSH"},
  {name:"Amik Robertson",pos:"CB",teamAbbr:"WSH"},
];
